---
title: "Descriptive plots from the data"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, include = FALSE, message = FALSE)
```


```{r load-packages}
library(here)
source(here("R/load_packages.R"))

fig.dir = here("figures/figure0")

if (!file.exists(fig.dir)) {
    dir.create(fig.dir)
}
```


```{r loading-the-input}
source(here("R/process_sigs_TCGA.R"))
source(here("R/process_sigs_PCAWG.R"))
```


```{r plotting-functions}
plot_tissue_abundance = function(tissue_counts, title, bar_height_factor = 2, 
                                 annot_x = 33) {
    tissue_counts %>%
    mutate(Cancer.Types = factor(Cancer.Types, levels = Cancer.Types)) %>% 
    ggplot(aes(x = Cancer.Types, y = n, fill = Cancer.Types)) + 
    geom_bar(stat = "identity") + 
    scale_fill_manual(
        values = c(unname(scales::muted(
            rainbow(tissue_counts %>% 
                        filter(n > MIN.TISSUE.SIZE) %>% nrow()), 
            l = 50, c = 90 )), 
                   rep("gray60", tissue_counts %>% 
                           filter(n < MIN.TISSUE.SIZE) %>% nrow() )  ) 
        ) +
    geom_hline(yintercept = MIN.TISSUE.SIZE, size = 0.5) +
    ylab("Samples") +
    # scale_fill_manual(values = scales::muted(
    #     rainbow(pcawg.active.sig.counts %>% pull(Tissues) %>% 
    #                 n_distinct()), l = 50, c = 90 ), guide = "none" ) + 
    theme_bw() +
    theme(panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
          axis.title.x = element_blank(),
          panel.border = element_blank(),
          legend.position = "none") +
    annotate("text", y = bar_height_factor * MIN.TISSUE.SIZE, x = annot_x,
             label = paste0(">", MIN.TISSUE.SIZE, " samples")) + 
        ggtitle(title)
}


plot_active_signatures = function(dt.input) {
    dt.sigs = dt.input %>% select(4:ncol(.))
    dt.active.sig.counts = data.frame(Tissues = dt.input$Cancer.Types,
                                      active.sig.counts = rowSums(dt.sigs > 0))
    
    tissue_abundance_order = sort(table(dt.active.sig.counts$Tissues), decreasing = FALSE)
    dt.active.sig.counts$Tissues = factor(dt.active.sig.counts$Tissues,
                                             levels = names(tissue_abundance_order) )
    
    active.sig.histogram = ggplot(dt.active.sig.counts, 
                                  aes(x = active.sig.counts, fill = Tissues)) +
        geom_histogram(binwidth = 1, color = "gray90") +
        theme_classic(base_size = 13) + 
        scale_x_continuous(breaks = seq(1, 11)) + 
        coord_cartesian(expand = FALSE) + 
        scale_fill_manual(values = scales::muted(
            rainbow(dt.active.sig.counts %>% pull(Tissues) %>% 
                        n_distinct()), l = 50, c = 90 ), guide = "none" ) +
        xlab("Active signatures") + ylab("Number of samples") + 
        theme(legend.position = c(1, 0.64), 
              plot.margin = margin(1.3, 3, 0.2, 0.2, "cm"))
    return(active.sig.histogram)
}
```


### Sample distribution across tissues

```{R pcawg-numbers}
pcawg_tissue_counts = PCAWG.filter_rec_acc %>% 
    select(Cancer.Types, Sample.Names) %>% 
    count(Cancer.Types, sort = TRUE)

pcawg_tissue_counts_plot = plot_tissue_abundance(pcawg_tissue_counts, 
                                                 "PCAWG - samples across tissues")
pcawg_tissue_counts_plot

ggsave(filename = file.path(fig.dir, "pcawg_tissue_counts_plot.png"),
    plot = pcawg_tissue_counts_plot, width = 5, height = 3)


ggsave(filename = file.path(fig.dir, "pcawg_tissue_counts_plot.pdf"),
    plot = pcawg_tissue_counts_plot, width = 5, height = 3)
```

In PCAWG we have `pcawg_tissue_counts %>% filter(n > 25) %>% summarise(sum = sum(n))`
samples.

```{R tcga-numbers}
tcga_tissue_counts = TCGA.filter_rec_acc %>% 
    select(Cancer.Types, Sample.Names) %>% 
    count(Cancer.Types, sort = TRUE)

tcga_tissue_counts_plot = plot_tissue_abundance(
    tcga_tissue_counts, bar_height_factor = 3,
    "TCGA - samples across tissues", 
    annot_x = 25)
tcga_tissue_counts_plot

ggsave(filename = file.path(fig.dir, "tcga_tissue_counts_plot.png"),
    plot = tcga_tissue_counts_plot, width = 5, height = 3)

ggsave(filename = file.path(fig.dir, "tcga_tissue_counts_plot.pdf"),
    plot = tcga_tissue_counts_plot, width = 4.5, height = 3)
```

In TCGA we have `tcga_tissue_counts %>% filter(n > 25) %>% summarise(sum = sum(n))`
samples.

### Number of active signatures across samples

```{r pcawg-active-hists}
pcawg.active.signatures.hist = plot_active_signatures(PCAWG.full.subset) + 
    ggtitle("PCAWG") + theme(plot.margin = unit(c(2,2,2,2), "mm"))

ggsave(pcawg.active.signatures.hist, 
       filename = file.path(fig.dir, "PCAWG.active.signatures.histogram.png"),
       width = 3, height = 3.6)

ggsave(pcawg.active.signatures.hist, 
       filename = file.path(fig.dir, "PCAWG.active.signatures.histogram.pdf"),
       width = 3, height = 3.6)


pcawg.active.signatures.hist.ann = plot_active_signatures(PCAWG.full.subset.ann) + 
    ggtitle("PCAWG") + theme(plot.margin = unit(c(2,2,2,2), "mm"))

ggsave(pcawg.active.signatures.hist.ann, 
       filename = file.path(fig.dir, "PCAWG.active.signatures.histogram.annotated.png"),
       width = 3, height = 3.6)

ggsave(pcawg.active.signatures.hist.ann, 
       filename = file.path(fig.dir, "PCAWG.active.signatures.histogram.annotated.pdf"),
       width = 3, height = 3.6)
```

### Most common signature counts

```{r}
pcawg.number.3.to.5.sigs = PCAWG.full.subset %>% 
    select(4:ncol(.)) %>% 
    mutate_all( ~ . > 0) %>% 
    rowwise() %>% 
    summarize(active_sigs = sum(c_across(everything()))) %>% 
    summarize(x = sum(active_sigs >= 3 & active_sigs <= 5))

pcawg.number.3.to.5.sigs / nrow(PCAWG.full.subset)
# [1] 0.7838672

pcawg.number.3.to.4.sigs.ann = PCAWG.full.subset.ann %>% 
    select(4:ncol(.)) %>% 
    mutate_all( ~ . > 0) %>% 
    rowwise() %>% 
    summarize(active_sigs = sum(c_across(everything()))) %>% 
    summarize(x = sum(active_sigs >= 3 & active_sigs <= 4))

pcawg.number.3.to.4.sigs.ann / nrow(PCAWG.full.subset.ann)
# [1] 0.7657275	

tcga.number.3.to.5.sigs = TCGA.full.subset %>% 
    select(4:ncol(.)) %>% 
    mutate_all( ~ . > 0) %>% 
    rowwise() %>% 
    summarize(active_sigs = sum(c_across(everything()))) %>% 
    summarize(x = sum(active_sigs >= 3 & active_sigs <= 5))
tcga.number.3.to.5.sigs / nrow(TCGA.full.subset)
# [1] 0.7789681


tcga.number.3.to.4.sigs.ann = TCGA.full.subset.ann %>% 
    select(4:ncol(.)) %>% 
    mutate_all( ~ . > 0) %>% 
    rowwise() %>% 
    summarize(active_sigs = sum(c_across(everything()))) %>% 
    summarize(x = sum(active_sigs >= 3 & active_sigs <= 4))

tcga.number.3.to.4.sigs.ann / nrow(TCGA.full.subset.ann)
# [1] 0.8063152
```


```{r pcawg-combined}
pcawg_combined = egg::ggarrange(pcawg_tissue_counts_plot, 
                              pcawg.active.signatures.hist, 
                          widths = c(5, 2.5),
                          labels = c("A", "B"))
ggsave(pcawg_combined, 
       filename = file.path(fig.dir, "pcawg_combined_counts.png"),
       width = 7, height = 3.6)
```



```{r tcga-active-hists}
tcga.active.signatures.hist = plot_active_signatures(TCGA.full.subset) + 
    ggtitle("TCGA") + theme(plot.margin = unit(c(2,2,2,2), "mm"))

ggsave(tcga.active.signatures.hist, 
       filename = file.path(fig.dir, "TCGA.active.signatures.histogram.png"),
       width = 3, height = 3.6)

ggsave(tcga.active.signatures.hist, 
       filename = file.path(fig.dir, "TCGA.active.signatures.histogram.pdf"),
       width = 3, height = 3.6)


tcga.active.signatures.hist.ann = plot_active_signatures(TCGA.full.subset.ann) + 
    ggtitle("TCGA") + theme(plot.margin = unit(c(2,2,2,2), "mm"))

ggsave(tcga.active.signatures.hist.ann, 
       filename = file.path(fig.dir, "TCGA.active.signatures.histogram.annotated.png"),
       width = 3, height = 3.6)

ggsave(tcga.active.signatures.hist.ann, 
       filename = file.path(fig.dir, "TCGA.active.signatures.histogram.annotated.pdf"),
       width = 3, height = 3.6)
```

```{r tcga-combined}
tcga_combined = egg::ggarrange(tcga_tissue_counts_plot, 
                              tcga.active.signatures.hist, 
                          widths = c(5, 2.5),
                          labels = c("A", "B"))
ggsave(tcga_combined, 
       filename = file.path(fig.dir, "tcga_combined_counts.png"),
       width = 7, height = 3.6)
```

