---
title: "Overview of all interactions"
output: 
  html_document:
    df_print: paged
---

```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```


```{r load-packages, message=FALSE, warning= FALSE}
library(here)
library(chrwiseSignatures)
fig.dir = here("figures/overview_networks")

if(! file.exists(fig.dir)){
    dir.create(fig.dir, recursive = TRUE)
}

source(here("R/load_packages.R"))
library(igraph)
library(tidygraph)
library(pheatmap)
library(viridis)
library(rlang)
```

### getting PCAWG summary network

```{r}
prep_the_data = function(dataset, cnames = "sig2") {
    dataset %>% rownames_to_column( var = "sig1") %>% 
        pivot_longer(cols = !sig1, names_to = cnames, values_to = "tissue") %>% 
        mutate(tissue = strsplit(as.character(tissue), ", ")) %>% 
        unnest(cols = c(tissue)) %>% 
        group_by(sig1, (!!sym(cnames))) %>% 
        summarize(count = n())
}

pcawg.pos.ints = read.table(
    file = here("supp_data", "PCAWG_positive_interaction_tissue_summaries.tsv"),
          row.names = 1, head  = T, sep = "\t")

pcawg.pos.ints  = pcawg.pos.ints %>% prep_the_data() %>% mutate(int.type = "positive")

pcawg.neg.ints = read.table(
    file = here("supp_data", "PCAWG_negative_interaction_tissue_summaries.tsv"),
          row.names = 1, head  = T, sep = "\t")

pcawg.neg.ints = pcawg.neg.ints %>% prep_the_data() %>% mutate(int.type = "negative")

pcawg.sig.sig.net = rbind(pcawg.pos.ints, pcawg.neg.ints) %>% 
    as_tbl_graph() %>% 
    activate(nodes) %>% 
    mutate(type = "sig")

pcawg.sig.path.pos = read.table(
    file = here("supp_data", "PCAWG_sig_pathway_positive_interaction_tissue_summaries.tsv"),
          row.names = 1, head  = T, sep = "\t")

pcawg.sig.path.pos = pcawg.sig.path.pos %>% prep_the_data(cnames = "path")%>% mutate(int.type = "positive")
    
pcawg.sig.path.neg = read.table(
    file = here("supp_data", "PCAWG_sig_pathway_negative_interaction_tissue_summaries.tsv"),
          row.names = 1, head  = T, sep = "\t")

pcawg.sig.path.neg = pcawg.sig.path.neg %>% prep_the_data(cnames = "path") %>% mutate(int.type = "negative")

path.names = unique(c(pcawg.sig.path.pos$path, pcawg.sig.path.neg$path))
    
pcawg.sig.path = rbind(pcawg.sig.path.pos, pcawg.sig.path.neg) %>% 
    as_tbl_graph() %>% 
    activate(nodes) %>% 
    mutate(type = ifelse(name %in% path.names, "path", "sig"))

all.pcawg.interactions = graph_join(pcawg.sig.sig.net, pcawg.sig.path)
```


### getting TCGA summary network

```{r}
prep_the_data = function(dataset, cnames = "sig2") {
    dataset %>% rownames_to_column( var = "sig1") %>% 
        pivot_longer(cols = !sig1, names_to = cnames, values_to = "tissue") %>% 
        mutate(tissue = strsplit(as.character(tissue), ", ")) %>% 
        unnest(cols = c(tissue)) %>% 
        group_by(sig1, (!!sym(cnames))) %>% 
        summarize(count = n())
}

tcga.pos.ints = read.table(
    file = here("supp_data", "TCGA_positive_interaction_tissue_summaries.tsv"),
          row.names = 1, head  = T, sep = "\t")

tcga.pos.ints  = tcga.pos.ints %>% prep_the_data() %>% mutate(int.type = "positive")

tcga.neg.ints = read.table(
    file = here("supp_data", "TCGA_negative_interaction_tissue_summaries.tsv"),
          row.names = 1, head  = T, sep = "\t")

tcga.neg.ints = tcga.neg.ints %>% prep_the_data() %>% mutate(int.type = "negative")

tcga.sig.sig.net = rbind(tcga.pos.ints, tcga.neg.ints) %>% 
    as_tbl_graph() %>% 
    activate(nodes) %>% 
    mutate(type = "sig")

tcga.sig.path.pos = read.table(
    file = here("supp_data", "TCGA_sig_pathway_positive_interaction_tissue_summaries.tsv"),
          row.names = 1, head  = T, sep = "\t")

tcga.sig.path.pos = tcga.sig.path.pos %>% prep_the_data(cnames = "path")%>% mutate(int.type = "positive")
    
tcga.sig.path.neg = read.table(
    file = here("supp_data", "TCGA_sig_pathway_negative_interaction_tissue_summaries.tsv"),
          row.names = 1, head  = T, sep = "\t")

tcga.sig.path.neg = tcga.sig.path.neg %>% prep_the_data(cnames = "path") %>% mutate(int.type = "negative")

path.names = unique(c(tcga.sig.path.pos$path, tcga.sig.path.neg$path))
    
tcga.sig.path = rbind(tcga.sig.path.pos, tcga.sig.path.neg) %>% 
    as_tbl_graph() %>% 
    activate(nodes) %>% 
    mutate(type = ifelse(name %in% path.names, "path", "sig"))

all.tcga.interactions = graph_join(tcga.sig.sig.net, tcga.sig.path)
```


```{r}
all.pcawg.interactions %>% 
    ggraph(layout = "kk") +
    geom_edge_link (aes(color = int.type), width = 0.5) +
    
    geom_node_label(aes(label = name, fill = type),
                    color = "gray10", 
                    label.size = 0, linewidth = 3, 
                    label.r = unit(0.2, "lines"),
                    label.padding = unit(0.2, "lines")) +
    
    scale_fill_manual(values = c("path" = "thistle3", "sig" = "palegreen3")) +
    
    scale_edge_color_manual(values = c("positive" = "red4",
                                       "negative" = "dodgerblue3")) + 
    theme_void() +
        theme(legend.position = "right", legend.title =element_blank() )
    


all.pcawg.interactions %>% 
    ggraph(layout = "circle") +
    geom_edge_link (aes(color = int.type), width = 0.5) +
    geom_node_point(aes(fill = type)) + 
    geom_node_label(aes(label = name#, fill = type
                        ),
                    color = "gray10", 
                    label.size = 0, linewidth = 3, 
                    label.r = unit(0.2, "lines"),
                    label.padding = unit(0, "lines"),
                   nudge_y = 0.2) +
    
    scale_fill_manual(values = c("path" = "thistle3", "sig" = "palegreen3")) +
    
    scale_edge_color_manual(values = c("positive" = "red4",
                                       "negative" = "dodgerblue3")) + 
    theme_void() +
        theme(legend.position = "right", legend.title =element_blank() )
```

### Playing around with dh layout 

```{r}
igraph_dh_mod = layout_with_dh()
layout <- create_layout(all.pcawg.interactions, layout = "dh", 
                        weight.border = 0.011,
                        weight.node.dist = 0.4,
                        weight.edge.crossings = 0.9,
                        weight.node.edge.dist = 0.4)

# ggraph(graph = layout) +
all.interactions.network = all.pcawg.interactions %>% ggraph(layout = "kk") +
    geom_edge_link (width = 0.6, color = "gray90") +
    
    # geom_edge_link (aes(color = int.type), width = 0.5) +
    #  scale_edge_color_manual(values = c("positive" = lighten("firebrick3", amount = 30),
    #                                    "negative" = lighten("dodgerblue3", amount = 30))) + 
    # 
    geom_edge_link (aes(color = int.type), width = 0.5) +
     scale_edge_color_manual(values = c("positive" = "firebrick3",
                                       "negative" = "dodgerblue3")) + 
    
    geom_node_label(aes(label = name, fill = type, color = type),
                    # color = "gray30", 
                    label.size = 0.1, 
                    size = 4, 
                    label.r = unit(0.2, "lines"),
                    label.padding = unit(0.2, "lines")) +
    
    scale_color_manual(values = c("path" = "gray30", "sig" = "white")) +
    
    scale_fill_manual(values = c("path" = "white", "sig" = "gray30")) +
    
    scale_edge_color_manual(values = c("positive" = "firebrick3",
                                       "negative" = "dodgerblue3")) + 
    theme_void() +
        theme(legend.position = "right", legend.title =element_blank())

ggsave( minor_plot(all.interactions.network, expand.factor = 0.05), 
       file = file.path(fig.dir,
                        "all.interactions.network.pdf"),
       width = 7, height = 6)
```

### Plotting only signatures

```{r}
layout <- create_layout(pcawg.sig.sig.net, layout = "kk"# , 
                        # bbox = 0, mds = FALSE
                        )


all.only.sig.network = pcawg.sig.sig.net %>% 
    ggraph(graph = layout) +
    geom_edge_link (aes(color = int.type), width = 0.5) +
    
    geom_node_label(aes(label = name),
                    color = "gray10", 
                    label.size = 0, size = 3, 
                    label.r = unit(0.2, "lines"),
                    label.padding = unit(0.1, "lines")) +
    
    scale_edge_color_manual(values = c("positive" = "red4",
                                       "negative" = "dodgerblue3")) + 
    theme_void() +
        theme(legend.position = "right", legend.title =element_blank() )

ggsave(all.only.sig.network, file = file.path(fig.dir,
                                              "all.only.sig.networks.pdf"),
       width = 6, height = 5)
```

```{r}
plot.mixed.layout = function(graph.input, 
                             central.nodes = c("Ageing" , "SBS5", "SBS40"),
                             circular.node.order = NULL, edge.width.breaks = NULL) {
    
    all.nodes = graph.input %>% 
        activate(nodes) %>% 
        as.data.frame() %>% 
        pull(name)
    
    graph.input = graph.input %>% 
        activate(nodes) %>% 
        mutate(annot.class = node.annotations %>% 
                   filter(sig.group %in% all.nodes) %>% 
                   select(Class, sig.group) %>% 
                   unique() %>% 
                   arrange(factor(sig.group, levels = all.nodes)) %>% 
                   pull(Class))
    
    circle.nodes = setdiff(all.nodes, central.nodes)
    # 
    # lay1 = layout_in_circle(induced_subgraph(graph.input, circle.nodes))
    # lay2 = layout_nicely(induced_subgraph(graph.input, central.nodes))
    # lay3 <- rbind(lay1 + 2, lay2 *  10) 
    # 
    
    central.subgraph = graph.input %>% 
        to_subgraph(name %in% central.nodes, subset_by = "nodes") 
    
    circle.subgraph = graph.input %>% 
        to_subgraph(name %in% circle.nodes, subset_by = "nodes") 
    
    lay.central = create_layout(central.subgraph$subgraph,
                                layout = "stress")
    
    if (is.null(circular.node.order)) {
        lay.circle = create_layout(circle.subgraph$subgraph,
                                   layout = "circle")
    } else {
        lay.circle = create_layout(circle.subgraph$subgraph,
                                   layout = "circle", order = circular.node.order)
    }
        
    # plot.igraph(pcawg.sig.sig.net, layout=lay3, vertex.size=8)
    
    node.coordinates = rbind(lay.central, lay.circle) %>% as.data.frame() %>% 
        arrange(factor(name, levels = all.nodes)) 
    pp = graph.input %>% ggraph(x = node.coordinates$x, y = node.coordinates$y) + 
        geom_edge_link (aes(color = int.type, width = count), alpha = 0.4) +
        scale_edge_width(edge.width.breaks, range = c(0.3,3)) +
        geom_node_point(aes(fill = annot.class), 
                        color = "gray30", 
                        size = 4,
                        shape = 21,
                        stroke = 0.6) + 
        geom_node_label(aes(label = name#, fill = type
                            ),
                        color = "gray10", 
                        label.size = 0,
                        hjust = ifelse(node.coordinates[,1] > 0, -0.25, 1.25),
                        vjust = ifelse(node.coordinates[,2] > 0, -0.3, 1.15),
                        # hjust = node.coordinates[ ,1] * 1.1,
                        # vjust = node.coordinates[ ,2] * 1.1,
                        label.r = unit(0.2, "lines"),
                        label.padding = unit(0, "lines"),
                       nudge_y = 0) + 
        scale_edge_color_manual(values = c("positive" = "red4",
                                           "negative" = "dodgerblue3")) + 
        scale_fill_manual(values = c("Endogenous" = "#CAE7B9",
                                      "Environmental" = "#f3de8a",
                                      # "Clock-like" = "#ff934f",
                                      "Clock-like" = "white",
                                      "Unknown" = "#4e6151") ) +
        theme_void() + 
        theme(legend.position = "right", legend.title =element_blank() )
    return(pp)
}
```


```{r pcawg-all-signatures}
node.order = c(sort(c("APOBEC", "MMR", "HR", "ROS", "PolH", "PolE")),
                
               sort(c("SBS39", "SBS19", "SBS23", "SBS28", "SBS17", "SBS30", 
                "SBS34", "SBS37", "SBS12", "Technical")),
               
               sort(c("Tobacco", "UV", "SBS38", "SBS29")))

node.annotations = data.frame(sig.group = c(node.order, c("Ageing", "SBS5", "SBS40")),
                              Class = c(rep("Endogenous", 6), 
                                        rep("Unknown", 10),
                                        rep("Environmental", 4),
                                        rep("Clock-like", 3))
                             )


pcawg.sig.sig.all.network = plot.mixed.layout(
    pcawg.sig.sig.net, 
    circular.node.order = node.order,
    edge.width.breaks = c(1,2,4,13)
    )


ggsave(plot = minor_plot(pcawg.sig.sig.all.network, expand.factor = 0.2),
       filename = file.path(fig.dir, "pcawg.sig.sig.all.network.pdf"),
       width = 6.4, height = 5.3)
```


```{r tcga-all-signatures}
node.order = c(sort(c("APOBEC", "MMR", "HR", "ROS", "PolH", "PolE")),
                
               sort(c("SBS39", "SBS19", "SBS23", "SBS28", "SBS17", "SBS30", 
                "SBS34", "SBS37", "SBS12", "Technical")),
               
               sort(c("Tobacco", "UV", "SBS38", "SBS29")))

node.annotations = data.frame(sig.group = c(node.order, c("Ageing", "SBS5", "SBS40")),
                              Class = c(rep("Endogenous", 6), 
                                        rep("Unknown", 10),
                                        rep("Environmental", 4),
                                        rep("Clock-like", 3))
                             )


tcga.sig.sig.all.network = plot.mixed.layout(
    tcga.sig.sig.net, 
    # circular.node.order = node.order,
    # edge.width.breaks = c(1,2,4,13)
    )


ggsave(plot = minor_plot(tcga.sig.sig.all.network, expand.factor = 0.2),
       filename = file.path(fig.dir, "tcga.sig.sig.all.network.pdf"),
       width = 6.4, height = 5.3)
```

