---
title: "Summarizing all signature-signature interactions PCAWG"
output: 
  html_document:
    df_print: paged
---

```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```

```{r load-packages, message=FALSE}
library(here)
fig.dir = here("figures/sig_sig_interactions")

if(! file.exists(fig.dir)){
    dir.create(fig.dir, recursive = TRUE)
}

source(here("R/load_packages.R"))
library(igraph)
library(tidygraph)
library(pheatmap)

data.out.dir = here("data/RDS/PCAWG", "sig_sig_ints")

output.dir = here("output/sig_sig_int_motifs")

```

```{r loading-precalc-interactions}

### These data is generated in here("R/sig_sig_interactions.PCAWG.R")

PCAWG.cooccurrence.summary.nets = readRDS(file = file.path(data.out.dir, "PCAWG.cooccurrence.summary.nets.RDS") )
PCAWG.bcmi.summary.nets = readRDS(file = file.path(data.out.dir, "PCAWG.bcmi.summary.nets.RDS") )
PCAWG.pearson.summary.nets = readRDS(file = file.path(data.out.dir, "PCAWG.pearson.summary.nets.RDS") )
PCAWG.spearman.summary.nets = readRDS(file = file.path(data.out.dir, "PCAWG.spearman.summary.nets.RDS") )
PCAWG.coda.summary.nets = readRDS(file = file.path(data.out.dir, "PCAWG.coda.summary.nets.RDS") )

PCAWG.full.subset.ann = readRDS(here("data", "RDS", "PCAWG", "signatures",
                                     "PCAWG.full.subset.ann.RDS"))

PCAWG.null.quants = readRDS(file.path(here("data", "RDS", "PCAWG", "signatures"),
                              "PCAWG.null.model.95.quants.RDS"))

for (tissue in names(PCAWG.null.quants)) {
    
    for (metric.name in names(PCAWG.null.quants[[tissue]])) {
        PCAWG.null.quants[[tissue]][[metric.name]] = 
            PCAWG.null.quants[[tissue]][[metric.name]] + t(PCAWG.null.quants[[tissue]][[metric.name]])
    }
}
```

```{r }
all.interactions = list(MI = PCAWG.bcmi.summary.nets,
                        cooccurrence = PCAWG.cooccurrence.summary.nets,
                        CoDa = PCAWG.coda.summary.nets,
                        Spearman = PCAWG.spearman.summary.nets)

tissues = unique(PCAWG.full.subset.ann$Cancer.Types)

```

```{r tissue-interaction-network}
tissue = "Panc_AdenoCA"
tissue.nets = get_tissue_dataset_networks(tissue, all.interactions, 
                                          filter.list = list(MI = 0.2),
                                          filter.mat = PCAWG.null.quants[[tissue]])
tissue.multi.graph = tissue_multi_graph(tissue.nets)

pp = print_multi_graphs(tissue.multi.graph, 
                   layout = "dh")

# max.degree.node = tissue.multi.graph %>% 
#     activate(nodes) %>% 
#     mutate(degree = centrality_degree(mode = "all")) %>% 
#     filter(degree == max(degree)) %>% 
#     pull(name)
# 
# pp = print_multi_graphs(tissue.multi.graph, 
#                    layout = "star", center = max.degree.node)

pout = minor_plot(pp, expand.factor = 0.05, expand.factor.y = 0)
print(pout)

ggsave(filename = file.path(fig.dir, paste0(tissue, "_sig_sig_network.png") ),
       plot = pout,
       width = 6, height = 4)

ggsave(filename = file.path(fig.dir, paste0(tissue, "_sig_sig_network.pdf") ),
       plot = pout,
       width = 6, height = 4)

# igraph_layouts <- c('star', 'circle', 'gem', 'dh', 'graphopt', 'grid', 'mds', 
#                     'randomly', 'fr', 'kk', 'drl', 'lgl')
# 
# pp.list = lapply(igraph_layouts, function(layout.name){
#     print_multi_graphs(tissue.multi.graph, 
#                    layout = layout.name) + ggtitle(layout.name)
# })
# 
# layouts.test = ggarrange(plotlist = pp.list, nrow = 2, ncol = 6)
# 
# ggsave(layouts.test, filename = file.path(fig.dir, "layouts.test.pdf" ),
#        width = 30, height = 8)
# 

```

```{r tissue-signatures-heatmap}
tissue.heatmap = subset_tissue(PCAWG.full.subset.ann, tissue = tissue) %>% 
    plot_tissue_heatmap(main = tissue, border_color = NA) %>% add_pheatmap_legend_title()

print(tissue.heatmap)

ggsave(filename = file.path(fig.dir, paste0(tissue, "_sig_heatmap.png") ), 
       plot = tissue.heatmap, width = 4, height = 5)
ggsave(filename = file.path(fig.dir, paste0(tissue, "_sig_heatmap.pdf") ), 
       plot = tissue.heatmap, width = 4, height = 5)
```


```{r all-tissue-heatmap-networks, include = FALSE}
plotlist = list()
i = 1
for (tissue in tissues) {
    cat(tissue, " ")

    try({
        tissue.heatmap = subset_tissue(PCAWG.full.subset.ann, tissue = tissue) %>% 
            plot_tissue_heatmap(main = tissue)
        # print(pp)
        
        pp = plot_multi_network(network.lists = all.interactions, 
                                tissue = tissue, 
                                filter.list = list(MI = 0.2),
                                filter.mat = PCAWG.null.quants[[tissue]],
                                layout = "stress")
        
        
        pp = minor_plot(pp, title = tissue, expand.factor = 0.1)
        
        out.plot = ggarrange(tissue.heatmap[[4]], pp, nrow = 1)
        i = i + 1
        plotlist[[i]] = out.plot
    })
}
```

```{r}
pdf(file.path(fig.dir, "PCAWG_heatmaps_multiple_networks_4types_SigProfiler_stress.pdf"),
    width = 10, height = 4)

for (i in 1:length(plotlist) ) {
    try({print(plotlist[[i]] ) })
}
dev.off()
```

```{r, include = FALSE}
for (metric in names(all.interactions)) {
    
    cat("\t metric = ", metric, "\n")
    metric.dir = file.path(output.dir, metric)
    if (!file.exists(metric.dir) ) {
        dir.create(metric.dir, showWarnings = FALSE, recursive = TRUE)
    }
        
    get_common_sigs(metric.list = all.interactions, 
                    metric = metric, outdir = metric.dir, threshold = 0.2)
}
```

### Plotting the summaries of interactions across cancer types

```{r concat-interactions}
PCAWG.networks.concat = list()

for (tissue in tissues) {
    cat(tissue, " ")
    
    try({
        PCAWG.networks.concat[[tissue]] = concat_networks(
            all.interactions, 
            tissue = tissue, 
            filter.list = list(MI = 0.2), 
            filter.mat = PCAWG.null.quants[[tissue]])
    })
}
```


```{r plotting-int-network}
sig.sig.ints.summary.plot.1 = plot_all_counts(PCAWG.networks.concat, min.abssum = 1,
                                            psize = 4.5, lsize = 1.7, 
                                            expand.mult = c(0.02, 0.02)) + 
    coord_cartesian(x = c(1, 20), clip = "off")

sig.sig.ints.summary.plot.3 = plot_all_counts(PCAWG.networks.concat, min.abssum = 3,
                                            psize = 4.5, lsize = 1.7, 
                                            expand.mult = c(0.02, 0.02)) + 
    coord_cartesian(x = c(1, 20), clip = "off")

ggsave(filename = file.path(fig.dir, paste0("PCAWG_sig_sig_ints_summary_plot_lim3.png") ),
       plot = sig.sig.ints.summary.plot,
       width = 3.7, height = 3.5)


sig.sig.ints.summary.plot.4 = plot_all_counts(PCAWG.networks.concat, min.abssum = 4,
                                            psize = 6, lsize = 2, 
                                            expand.mult = c(0.02, 0.02)) + 
    coord_cartesian(x = c(1, 16), clip = "off")

cairo_pdf(filename = file.path(fig.dir, paste0("PCAWG_sig_sig_ints_summary_plot_lim4_cairo.pdf") ),
          width = 3.8, height = 3.6)
print(sig.sig.ints.summary.plot.4)
dev.off()


sig.sig.ints.summary.plot.5 = plot_all_counts(PCAWG.networks.concat, min.abssum = 5,
                                            psize = 6, lsize = 2, 
                                            expand.mult = c(0.02, 0.02)) + 
    coord_cartesian(x = c(1, 13), clip = "off")

ggsave(filename = file.path(fig.dir, paste0("sig_sig_ints_summary_plot_lim5.png") ),
       plot = sig.sig.ints.summary.plot,
       width = 3.7, height = 3.5)

ggsave(filename = file.path(fig.dir, paste0("sig_sig_ints_summary_plot_lim5.pdf") ),
       plot = sig.sig.ints.summary.plot,
       width = 3.7, height = 3.5)

cairo_pdf(filename = file.path(fig.dir, paste0("PCAWG_sig_sig_ints_summary_plot_lim5_cairo.pdf") ),
          width = 3.7, height = 3.5)
print(sig.sig.ints.summary.plot)
dev.off()
# concat.summaries = summarize_by_tissues(PCAWG.networks.concat)
```


### Getting and writing cancer types where individual interactions are active

```{r tissues-with-interactions}
PCAWG.int.tissues = get_interaction_tissues(PCAWG.networks.concat)


write.table(as.data.frame(PCAWG.int.tissues$pos.tissues), 
          file = here("supp_data", "PCAWG_positive_interaction_tissue_summaries.tsv"),
          row.names = TRUE, col.names = NA, sep = "\t", quote = FALSE)
write.table(as.data.frame(PCAWG.int.tissues$neg.tissues), 
          file = here("supp_data", "PCAWG_negative_interaction_tissue_summaries.tsv"),
          row.names = TRUE, col.names = NA, sep = "\t", quote = FALSE)
```
