---
title: "Immune states in PCAWG"
output:
  html_document:
    df_print: paged
---

```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 5, echo = FALSE, 
                      warning = FALSE, message = FALSE)
```


```{r load-packages}
library(here)
fig.dir = here("figures/immune_analysis")


for (dir.path in c(fig.dir, file.path( fig.dir, 
                                  "immune_to_signature", "by_tissues", "oddsratio"))) {
    if(! file.exists(dir.path)){
        dir.create(dir.path, recursive = TRUE)
    }   
}


source(here("R/load_packages.R"))

out.dir = here("data/RDS/PCAWG/immune_states")
```

```{r}
immune.states = readRDS(file = file.path(out.dir, "pcawg_immune_states.RDS"))

majority.stats = apply(immune.states[4:6], MARGIN = 1, 
                       function(x) {
                           tt = table(x); 
                           ind = which.max(tt); 
                           c(names(tt)[ind], tt[ind] / length(x)) 
                           }) %>% t() %>% as.data.frame() 
colnames(majority.stats) = c("Majority", "Prop")


immune.states = cbind(immune.states, majority.stats)    


PCAWG.full.subset.ann.immune= readRDS(
    file = file.path(out.dir, "PCAWG.full.subset.ann.immune.RDS"))

ssGSEA = readRDS(file = file.path(out.dir, "ssGSEA_pcawg.RDS"))
```

### Summary of immune states

```{r}
table(immune.states[, c("RF", "DN")]) %>% 
    as.data.frame() %>% 
    ggplot(aes(x = RF, y = DN, fill = Freq)) + 
    geom_tile() + 
    geom_text(aes(label = Freq), color = "white") + 
    scale_fill_viridis() + ggtitle("RF vs DN")
```

```{r}
table(immune.states[, c("RF", "XGboost")]) %>% 
    as.data.frame() %>% 
    ggplot(aes(x = RF, y = XGboost, fill = Freq)) + 
    geom_tile() + 
    geom_text(aes(label = Freq), color = "white") + 
    scale_fill_viridis() + ggtitle("RF vs XGboost")
```

```{r}
table(immune.states[, c("DN", "XGboost")]) %>% 
    as.data.frame() %>% 
    ggplot(aes(x = DN, y = XGboost, fill = Freq)) + 
    geom_tile() + 
    geom_text(aes(label = Freq), color = "white") + 
    scale_fill_viridis() + ggtitle("DN vs XGboost")
```
### ssGSEA value processing

```{r}
ssGSEA = t(ssGSEA)

ssGSEA = as.data.frame(ssGSEA[immune.states$sample_id, ])
rownames(ssGSEA) = rownames(immune.states)

immune.data = cbind(immune.states, ssGSEA)
```


### Comparing the PCAWG classes

```{r}
ssGSEA_pivot = immune.data %>% pivot_longer(cols = LIexpression_score:CHANG_CORE_SERUM_RESPONSE_UP,
                                names_to = "pathway", values_to = "ssGSEA")
```


```{r, fig.width = 10}
RF.ssGSEA = ssGSEA_pivot %>% 
    ggplot(aes(x = RF, y = ssGSEA, fill = RF)) + 
    geom_boxplot() + 
    facet_wrap(~pathway, scales = "free_y") + 
    scale_fill_discrete() + ggtitle("RF predictions")
print(RF.ssGSEA)
```


```{r, fig.width = 10}
DN.ssGSEA = ssGSEA_pivot %>% 
    ggplot(aes(x = DN, y = ssGSEA, fill = DN)) + 
    geom_boxplot() + 
    facet_wrap(~pathway, scales = "free_y") + 
    scale_fill_discrete() + ggtitle("DN predictions")
print(DN.ssGSEA)
```


```{r, fig.width = 10}
xgboost.ssGSEA = ssGSEA_pivot %>% 
    ggplot(aes(x = XGboost, y = ssGSEA, fill = XGboost)) + 
    geom_boxplot() + 
    facet_wrap(~pathway, scales = "free_y") + 
    scale_fill_discrete() + ggtitle("XGboost predictions")
print(xgboost.ssGSEA)
```


```{r, fig.width = 10}
Majority.ssGSEA = ssGSEA_pivot %>% 
    ggplot(aes(x = Majority, y = ssGSEA, fill = Majority)) + 
    geom_boxplot() +
    facet_wrap(~pathway, scales = "free_y") + 
    theme_bw(base_size = 13) + 
    scale_fill_discrete() + ggtitle("Majority predictions")
print(Majority.ssGSEA)
ggsave(plot = Majority.ssGSEA, 
       file = file.path(fig.dir, "Majority_vote_ssGSEA_boxplots.png"),
       width = 11, height = 5.5)
```

### Immune states across cancer types

```{r}
pcawg.immune.summaries.gg = immune.states %>% 
    group_by(Cancer.Types, Majority) %>% 
    count( Cancer.Types, Majority, name = "total") %>% ungroup() %>% 
    tidyr::complete(Cancer.Types, Majority, fill = list(total = 0))

immune.class.mapping = c("C1" = "Wound healing",
                         "C2" = "INF-\u03B3 dominant",
                         "C3" = "Inflammatory",
                         "C4" = "Lymphocyte depleted",
                         "C5" = "Immunologically quiet",
                         "C6" = "TGF-\u03B2 dominant",
                         "CNA" = "CNA")

pcawg.immune.summaries.gg$Immune.type = immune.class.mapping[pcawg.immune.summaries.gg$Majority]
pcawg.immune.summaries.gg$Immune.type = factor(pcawg.immune.summaries.gg$Immune.type,
                                               # levels = c("CNA", "TGF-β dominant",
                                               #            "Immunologically quiet",
                                               #            "Lymphocyte depleted",
                                               #            "Inflammatory",
                                               #            "INF-γ dominant",
                                               #            "Wound healing")
                                               levels = c("Wound healing", "INF-γ dominant",
                                                          "Inflammatory", "Lymphocyte depleted",
                                                          "Immunologically quiet", "TGF-β dominant",
                                                          "CNA"))

pcawg.immune.states.plot = pcawg.immune.summaries.gg %>% 
    rename(Counts = total) %>% 
    # mutate(Pathway = factor(Pathway, levels = path.order)) %>% 
    
    ggplot(aes(x = Immune.type, y = Cancer.Types) ) + 
        geom_tile(aes(fill = Counts), color = "gray80") +
        geom_text(aes(label = Counts), size = 3.4) + 
    #scale_fill_viridis(option = "plasma")
    scale_fill_gradient(low = "aliceblue", high = "orange") + 
    scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
    theme_minimal(base_size = 14) + 
    xlab("") + ylab("") + 
    ggtitle("Immune classes across cancer types",) +
    theme(panel.grid = element_blank(),
          axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          legend.position = "none",
          plot.title = element_text(size = 12),
          plot.margin = margin(t = 0,  # Top margin
                             r = 0,  # Right margin
                             b = 0,  # Bottom margin
                             l = 0)) # Left margin)

ggsave(plot = pcawg.immune.states.plot, 
     file = file.path(fig.dir, "pcawg.immune.states.heatmap.png"),
                      width = 5, height = 5, bg = "white")

cairo_pdf(filename = file.path(fig.dir, "pcawg.immune.states.heatmap.pdf"),
        width = 4.6, height = 5)
print(pcawg.immune.states.plot)
dev.off()

# ggsave(plot = pcawg.immune.states.plot, 
#      file = file.path(fig.dir, "pcawg.immune.states.heatmap.pdf"),
#                       width = 5, height = 5)
```

### Immune states and pathway interactions

```{r}
immune.states.tissues = immune.states %>% 
    pivot_wider(id_cols = c(sample_id, donor_id, Cancer.Types), 
                 names_from = Majority, values_from = Prop) %>% 
    mutate(across(C2:C5, ~ifelse(is.na(.), 0, .))) %>% 
    mutate(across(C2:C5, ~ifelse(. > 0, 1, .))) %>% 
    mutate(across(C2:C5, as.integer))
```


```{r}
immune.tissue.odds.ratio = sig_pathway_int(sigs.input = PCAWG.full.subset.ann.immune,
                                 pathways.input = immune.states.tissues,
                                 interaction_function = get_sig_path_assocs, 
                                 path.min.tissues = 30,
                                 p.val.threshold = 0.2,
                                 p.adjust = TRUE,
                                 method = "BH")


for (tissue in names(immune.tissue.odds.ratio)) {
   
    if (any(abs(immune.tissue.odds.ratio[[tissue]]) > 0) ) {
        cat(tissue, "\n")
        int.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio[[tissue]], 
                                        title = tissue)
        
        ggsave(plot = int.heatmap,
               filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                                    paste0("PCAWG_", tissue, "_sig_pathway.dotplot.png")),
               height = 5, width = 6, bg = "white")
    }
}
```

```{r}
immune.tissue.odds.ratio.unadjusted = sig_pathway_int(sigs.input = PCAWG.full.subset.ann.immune,
                                 pathways.input = immune.states.tissues,
                                 interaction_function = get_sig_path_assocs, 
                                 path.min.tissues = 30,
                                 p.val.threshold = 0.05,
                                 p.adjust = FALSE,
                                 method = "BH")


for (tissue in names(immune.tissue.odds.ratio.unadjusted)) {
   
    if (any(abs(immune.tissue.odds.ratio.unadjusted[[tissue]]) > 0) ) {
        cat(tissue, "\n")
        int.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio.unadjusted[[tissue]], 
                                        title = tissue)
        
        ggsave(plot = int.heatmap,
               filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                                    paste0("PCAWG_", tissue, "_sig_pathway_unadjusted.dotplot.png")),
               height = 5, width = 6, bg = "white")
    }
}
```

```{r}

immune.OR.plot.input = immune.tissue.odds.ratio.unadjusted

for (tissue in names(immune.OR.plot.input) ) {
    if (length(immune.OR.plot.input[[tissue]]) == 0) {
        next
    }
    colnames(immune.OR.plot.input[[tissue]]) = immune.class.mapping[ colnames(immune.OR.plot.input[[tissue]]) ]
}
 
pp.immune.odds.ratio.unadjusted = plot_all_counts(immune.OR.plot.input, 
                                                  threshold = 0.2, psize = 5, 
                                                  expand.mult = c(0.06, 0.06)) + 
    coord_cartesian(x = c(1, 7), clip = "off")

ggsave(plot = pp.immune.odds.ratio.unadjusted,
               filename = file.path(fig.dir,
                                    "PCAWG_summarized_immune_sig_unadjusted.dotplot.pdf"),
               height = 1.1, width = 2.5, bg = "white", device = cairo_pdf)
```


```{r}

immune.tissues.odds.ratio.lists = get_interaction_tissues(immune.tissue.odds.ratio.unadjusted)

write.table(as.data.frame(immune.tissues.odds.ratio.lists$pos.tissues), 
          file = here("supp_data", "PCAWG_sig_immune_positive_interaction_tissue_summaries.tsv"),
          row.names = TRUE, col.names = NA, sep = "\t", quote = FALSE)
write.table(as.data.frame(immune.tissues.odds.ratio.lists$neg.tissues), 
          file = here("supp_data", "PCAWG_sig_immune_negative_interaction_tissue_summaries.tsv"),
          row.names = TRUE, col.names = NA, sep = "\t", quote = FALSE)

```




```{r}
tissue = "ColoRect_AdenoCA" 

colnames(immune.tissue.odds.ratio[[tissue]]) = c("Wound\nhealing", "INF-\u03B3\ndominant")

colorectal.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio[[tissue]], 
                                        title = tissue)

ggsave(plot = colorectal.heatmap,
       filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                            paste0(tissue, "_sig_pathway.dotplot.pdf")),
       height = 4, width = 4, bg = "white")


cairo_pdf(filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                            paste0("PCAWG_", tissue, "_sig_pathway.dotplot.pdf")),
          height = 4, width = 4)
print(colorectal.heatmap)
dev.off()
```

### Venn diagram of immune state prediction with different methods


```{r}
library(ggVennDiagram)

x = list(RandomForest = paste(1:length(immune.states$RF), immune.states$RF, sep = "_"),
         DNN = paste(1:length(immune.states$DN), immune.states$DN, sep = "_"),
         XGBoost = paste(1:length(immune.states$XGboost), immune.states$XGboost, sep = "_"))

ggVennDiagram(x)

devtools::install_github("nicolash2/ggvenn")

ggplot() + geom_venn(x)


library(eulerr)

euler.calcs = euler(x)

venn.summary = plot(euler.calcs,
     quantities = TRUE,
     labels = list(font = 4))

ggsave(plot = venn.summary, filename = file.path(fig.dir, "venn_of_three_methods.pdf"),
       width = 4, height = 3)
```



```{r}
pcawg.immune.state.summary = immune.states %>% 
    ggplot(aes(x = Majority, y = after_stat(count))) + 
    geom_bar(fill = "dodgerblue4") + 
    theme_classic() + 
    scale_x_discrete(labels = c("C1" = "Wound healing",
                         "C2" = "INF-\u03B3\ndominant",
                         "C3" = "Inflammatory",
                         "C4" = "Lymphocyte\ndepleted",
                         "C5" = "Immunologically\nquiet",
                         "C6" = "TGF-\u03B2 dominant",
                         "CNA" = "CNA")) + 
    theme(axis.text.x = element_text(angle = 90, v = 0.5, h = 1, size = 13),
          axis.title.x = element_blank(),
          plot.margin = margin(1, 0,0,0, "cm") ) + 
    geom_text(stat='count', aes(label=..count..), vjust=-1) + 
    ylim(0,600)

ggsave(plot = pcawg.immune.state.summary, 
       filename = file.path(fig.dir,"pcawg.immune.state.summaries.pdf"),
       width = 4, height = 4, device = cairo_pdf)
```


```{r}
immune.states.tissues = data.frame(immune.states.tissues)


colnames(immune.states.tissues) = sapply( colnames(immune.states.tissues), 
                                          function(x) 
                                              {
                                              if (x %in% names(immune.class.mapping )) 
                                                  {
                                                  return(immune.class.mapping[x])
                                                  } else {
                                                      return(x)}
                                              }
                                          )


pathways_signatures_heatmap(tissue = "ColoRect_AdenoCA",
                            signatures = PCAWG.full.subset.ann.immune,
                            pathways = immune.states.tissues)
```



