---
title: "Survival analysis of signature-signature interactions in PCAWG"
output: 
  html_document:
    df_print: paged
---

```{r}
# .rs.restartR()
rm(list = ls())
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```

```{r load-packages, echo = FALSE, message=FALSE}
library(here)
library(survival)
library(survminer)

source(here("R/load_packages.R"))
library(gridExtra)
library(nonnestcox)

input.dir = here("data/RDS/PCAWG/metadata")

out.dir = here("data/RDS/PCAWG/sig_sig_survivals")
fig.dir = here("figures/sig_sig_survivals")

for (dir.name in c(fig.dir, out.dir)) {
    if (! file.exists(dir.name) ) {
        dir.create(dir.name, recursive = TRUE)
    }
}
```

### Reading in clinical and signature data

```{r}
PCAWG.full.subset.ann = readRDS(file = here("data/RDS",
                                           "PCAWG/signatures/PCAWG.full.subset.ann.RDS"))   
PCAWG.clin.df = readRDS(file = file.path(input.dir, "PCAWG.clin.df.RDS") )

positive.sig.sig = read.delim(file = here("supp_data", 
                                        "PCAWG_positive_interaction_tissue_summaries.tsv"),
                              row.names = 1)

negative.sig.sig = read.delim(file = here("supp_data", 
                                        "PCAWG_negative_interaction_tissue_summaries.tsv"),
                            row.names = 1)
```

### Survival models for positive interactions

```{r}
pos.plotlist = get_surv_plotlist(positive.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "PCAWG_positive_interactions_survivals_totmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()


pos.plotlist = get_surv_plotlist(positive.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "PCAWG_positive_interactions_survivals_nontotmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()


pos.plotlist = get_surv_plotlist(positive.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = TRUE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "PCAWG_positive_interactions_survivals_totmut_binary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()


pos.plotlist = get_surv_plotlist(positive.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8),
                                 epistatic = TRUE)

pdf(file.path(fig.dir, "PCAWG_positive_interactions_survivals_epistatic.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()
```


```{r}
pos.coxlist = get_surv_coxlist(positive.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(pos.coxlist, file = file.path(out.dir, "pos.coxlist.totmut.nonbinary.RDS"))


pos.coxlist = get_surv_coxlist(positive.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(pos.coxlist, file = file.path(out.dir, "pos.coxlist.nototmut.nonbinary.RDS"))
```


```{r}
# pos.picked.models = get_surv_best_model(positive.sig.sig, 
#                                  dataset = PCAWG.full.subset.ann,
#                                  clin.df = PCAWG.clin.df,
#                                  with.total.muts = TRUE, 
#                                  tmb.logged = TRUE,
#                                  binary.status = FALSE)
# saveRDS(pos.picked.models, file = file.path(out.dir, "pcawg.pos.sig.sig.picked.models.RDS"))
pos.picked.models.epi = get_surv_best_model(sig.sig.tissues.matrix = positive.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 param.list = list( 
                                     "age.at.diagnosis" = c(TRUE, FALSE),
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(TRUE, FALSE),
                                     "epistatic" = c(TRUE, FALSE)),
                                 min.sample.fraction = 0)

saveRDS(pos.picked.models.epi, file = file.path(out.dir, "pcawg.pos.sig.sig.picked.models.epi.RDS"))

pos.picked.models = get_surv_best_model(sig.sig.tissues.matrix = positive.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 param.list = list(
                                     "age.at.diagnosis" = c(TRUE, FALSE),
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(TRUE, FALSE),
                                     "epistatic" = c(FALSE)),
                                 min.sample.fraction = 0)

saveRDS(pos.picked.models, file = file.path(out.dir, "pcawg.pos.sig.sig.picked.models.RDS"))
# pos.picked.models %>% HR_summary_for_all(type = "pos") %>% plot_sigint_forest()
```


### Survival models for negative interactions

```{r}
neg.plotlist = get_surv_plotlist(negative.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "PCAWG_negative_interactions_survivals_totmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()


neg.plotlist = get_surv_plotlist(negative.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "PCAWG_negative_interactions_survivals_nontotmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()


neg.plotlist = get_surv_plotlist(negative.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 binary.status = TRUE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "PCAWG_negative_interactions_survivals_totmut_binary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()



neg.plotlist = get_surv_plotlist(negative.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8),
                                 epistatic = TRUE)

pdf(file.path(fig.dir, "PCAWG_negative_interactions_survivals_epistatic.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()
```

```{r}
neg.coxlist = get_surv_coxlist(negative.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(neg.coxlist, file = file.path(out.dir, "neg.coxlist.totmut.nonbinary.RDS"))

neg.coxlist = get_surv_coxlist(negative.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(neg.coxlist, file = file.path(out.dir, "neg.coxlist.nototmut.nonbinary.RDS"))

```

```{r}
neg.picked.models.epi = get_surv_best_model(sig.sig.tissues.matrix = negative.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 param.list = list( 
                                     "age.at.diagnosis" = c(TRUE, FALSE),
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(TRUE, FALSE),
                                     "epistatic" = c(FALSE)),
                                 min.sample.fraction = 0)

saveRDS(neg.picked.models.epi, file = file.path(out.dir, "pcawg.neg.sig.sig.picked.models.epi.RDS"))

neg.picked.models = get_surv_best_model(sig.sig.tissues.matrix = negative.sig.sig, 
                                 dataset = PCAWG.full.subset.ann,
                                 clin.df = PCAWG.clin.df,
                                 param.list = list(
                                     "age.at.diagnosis" = c(TRUE, FALSE),
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(TRUE, FALSE),
                                     "epistatic" = c(FALSE)),
                                 min.sample.fraction = 0)

saveRDS(neg.picked.models, file = file.path(out.dir, "pcawg.neg.sig.sig.picked.models.RDS"))

# neg.picked.models %>% HR_summary_for_all(type = "neg") %>% plot_sigint_forest()
```

### Specific interactions

```{r}
mult_tissues_ROS_SBS40 = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c( "SBS40", "ROS"), 
                                                      tissues = c("Prost_AdenoCA", "Panc_AdenoCA", "CNS_Medullo", 
                                                                  "Ovarian_AdenoCA"), 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.9, 0.9),
                                                      with.total.muts = TRUE,
                                                   tmb.logged = TRUE,
                                                      binary.status = FALSE)

mult_tissues_ROS_SBS40_adjusted = ggadjustedcurves(mult_tissues_ROS_SBS40$coxout, 
                 variable = "status", 
                 data = mult_tissues_ROS_SBS40$survival.df)


ggsave(plot = mult_tissues_ROS_SBS40_adjusted + theme(plot.margin = unit(c(0, 1.5, 0,0), units = "cm") ),
       filename = file.path(fig.dir, "PCAWG_mult_tissues_SBS40_ROS.survivals.pdf"),
       width = 4, height = 3.5)


mult_tissues_ROS_SBS40_ggforest = ggforest(model = mult_tissues_ROS_SBS40$coxout, data = mult_tissues_ROS_SBS40$survival.df)


ggsave(plot = mult_tissues_ROS_SBS40_ggforest,
       filename = file.path(fig.dir, "PCAWG_mult_tissues_SBS40_ROS.ggforest.pdf"),
       width = 6, height = 2.9)



eso_APOBEC_HR = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c("APOBEC", "HR"), 
                                                      tissues = "Eso_AdenoCA", 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.9, 0.9),
                                                      with.total.muts = FALSE,
                                                      tmb.logged = TRUE,
                                                      binary.status = FALSE)

ggsave(plot = eso_APOBEC_HR$survP$plot + theme(plot.margin = unit(c(4,4,4,4), units = "mm")) + 
           theme(plot.margin = unit(x = c(0.5, 2, 0, 0), units = "cm")),
       filename = file.path(fig.dir, "PCAWG_Eso_APOBEC_HR.survivals.pdf"),
       width = 4, height = 3.5)


APOBEC_HR_eso_ggforest = ggforest(model = eso_APOBEC_HR$coxout, data = eso_APOBEC_HR$survival.df)


ggsave(plot = APOBEC_HR_eso_ggforest,
       filename = file.path(fig.dir, "PCAWG_Eso_APOBEC_HR.ggforest.pdf"),
       width = 6, height = 2.2)


eso_APOBEC_SBS40 = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c("APOBEC", "SBS40"), 
                                                      tissues = "Eso_AdenoCA", 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.34, 0.22),
                                                      with.total.muts = TRUE,
                                                      tmb.logged = TRUE,
                                                      binary.status = FALSE)

ggsave(plot = eso_APOBEC_SBS40$survP$plot,
       filename = file.path(fig.dir, "PCAWG_Eso_AdenoCA_APOBEC_SBS40.pdf"),
       width = 3.6, height = 3.3)

eso_SBS40_HR = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c("SBS40", "HR"), 
                                                      tissues = "Eso_AdenoCA", 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.8, 0.8),
                                                      with.total.muts = TRUE,
                                                      tmb.logged = TRUE,
                                                      binary.status = FALSE)

ggsave(plot = eso_SBS40_HR$survP$plot,
       filename = file.path(fig.dir, "PCAWG_Eso_AdenoCA_SBS40_HR.pdf"),
       width = 3.6, height = 3.3)
```

```{r}
# Eso_AdenoCA :: APOBEC + SBS40
eso_APOBEC_SBS40 = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c("SBS40", "APOBEC"), 
                                                      tissues = "Eso_AdenoCA", 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.8, 0.8),
                                                      with.total.muts = TRUE,
                                                      tmb.logged = TRUE,
                                                      binary.status = FALSE,
                                             conf.int = TRUE)
```


```{r}
medulo_ROS_SBS40 = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c("SBS40", "ROS"), 
                                                      tissues = "CNS_Medullo", 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.8, 0.8),
                                                      with.total.muts = TRUE,
                                                      tmb.logged = TRUE,
                                                      binary.status = TRUE,
                                             conf.int = TRUE)
```


```{r}
eso_ROS_SBS17 = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c("SBS17", "ROS"), 
                                                      tissues = "Eso_AdenoCA", 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.8, 0.8),
                                                      with.total.muts = TRUE,
                                                      tmb.logged = TRUE,
                                                      binary.status = TRUE,
                                             conf.int = TRUE)


eso_ROS_SBS17_forest = ggforest(model = eso_ROS_SBS17$coxout, data = eso_ROS_SBS17$survival.df)
```



```{r}
ov_HR_SBS40 = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c("SBS40", "HR"), 
                                                      tissues = "Ovary_AdenoCA", 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.8, 0.8),
                                                      with.total.muts = FALSE,
                                                      tmb.logged = TRUE,
                                                      binary.status = FALSE,
                                             conf.int = TRUE)


ov_HR_SBS40_forest = ggforest(model = ov_HR_SBS40$coxout, data = ov_HR_SBS40$survival.df)
```


```{r}
panc_ROS_SBS5 = survival_for_interactions(dataset = PCAWG.full.subset.ann, 
                                                      signatures = c("SBS40", "HR"), 
                                                      tissues = "Ovary_AdenoCA", 
                                                      clin.df = PCAWG.clin.df,
                                                      legend_pos = c(0.8, 0.8),
                                                      with.total.muts = FALSE,
                                                      tmb.logged = TRUE,
                                                      binary.status = FALSE,
                                             conf.int = TRUE)
```

