---
title: "Signalling pathways in PCAWG"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, include = FALSE, message = FALSE)
```


```{r load-packages}
fig.dir = here("figures/figure0")

source(here("R/load_packages.R"))
```

```{r loading}
mutated_pathways_tissues = readRDS(file = here("data/RDS/PCAWG/10_onco_pathways",
                                              "pcawg_pathways.RDS"))

PCAWG.full.subset.ann.pathways = readRDS(file = here("data/RDS/PCAWG/10_onco_pathways",
                                              "PCAWG.full.subset.ann.pathways.RDS"))
```

### Heatmap of cancer types and pathways

```{r}
pathway_summaries_by_tissues = mutated_pathways_tissues %>% 
    mutate(across(`Cell Cycle`:Telomeric, ~as.numeric(.x > 0))) %>% 
    group_by(Cancer.Types) %>% 
    summarize(across(`Cell Cycle`:Telomeric, sum))

pcawg_pathway_summaries_gg = pathway_summaries_by_tissues  %>% 
    gather("Pathway", "Activity", -Cancer.Types) %>% 
    group_by(Cancer.Types, Pathway) %>% 
    summarise(total = sum(Activity))

path_order = pcawg_pathway_summaries_gg %>% 
    select(Pathway, total) %>% 
    group_by(Pathway) %>% 
    summarise(ss = sum(total)) %>% 
    arrange(desc(ss)) %>% 
    pull(Pathway)

pcawg_pathways_plot = pcawg_pathway_summaries_gg %>% rename(Counts = total) %>% 
    mutate(Pathway = factor(Pathway, levels = path_order)) %>% 
    
    ggplot(aes(x = Pathway, y = Cancer.Types) ) + 
        geom_tile(aes(fill = Counts), color = "gray80") +
        geom_text(aes(label = Counts), size = 3.4) + 
    #scale_fill_viridis(option = "plasma")
    scale_fill_gradient(low = "aliceblue", high = "orange") + 
    theme_minimal(base_size = 14) + 
    xlab("") + ylab("") + 
    ggtitle("Pathway alterations across tissues",) +
    theme(panel.grid = element_blank(),
          axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          legend.position = "none",
          plot.title = element_text(size = 12))
   

print(pcawg_pathways_plot)

ggsave(plot = pcawg_pathways_plot, 
       filename = file.path(fig.dir, "pcawg_pathways_summary.png"),
      width = 5, height = 6.2) 
```

