---
title: "Survival analysis of signature-signature interactions in PCAWG"
output: 
  html_document:
    df_print: paged
---

```{r}
rm(list = ls())
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```

```{r load-packages}
library(here)
library(survival)
library(survminer)

source(here("R/load_packages.R"))
library(gridExtra)

input.dir = here("data/RDS/PCAWG/metadata")


out.dir = here("data/RDS/PCAWG/sig_pathway_survivals")
fig.dir = here("figures/sig_pathway_survivals")

for (dir.name in c(fig.dir, out.dir)) {
    if (! file.exists(dir.name) ) {
        dir.create(dir.name, recursive = TRUE)
    }
}
```

### Reading in clinical and signature data

```{r}
PCAWG.full.subset.ann.pathways = readRDS(file = here("data/RDS/PCAWG/10_onco_pathways",
                                              "PCAWG.full.subset.ann.pathways.RDS"))

PCAWG.pathways.tissues = readRDS(file = here("data/RDS/PCAWG/10_onco_pathways",
                                              "pcawg_pathways.RDS"))

colnames(PCAWG.pathways.tissues) = gsub("[ -]", ".", colnames(PCAWG.pathways.tissues))


if (all.equal(rownames(PCAWG.full.subset.ann.pathways), rownames(PCAWG.pathways.tissues))) {

    PCAWG.path.sig.aggregate = cbind(PCAWG.full.subset.ann.pathways, 
                                     PCAWG.pathways.tissues[4:ncol(PCAWG.pathways.tissues)])
} else {
    stop("Rownames of pathway and signature dataframes do not match.\n")
}


PCAWG.clin.df = readRDS(file = file.path(input.dir, "PCAWG.clin.df.RDS") )

positive.sig.pathway = read.delim(file = here("supp_data", 
                                        "PCAWG_sig_pathway_positive_interaction_tissue_summaries.tsv"),
                              row.names = 1, na.strings = "")

negative.sig.pathway = read.delim(file = here("supp_data", 
                                        "PCAWG_sig_pathway_negative_interaction_tissue_summaries.tsv"),
                            row.names = 1, na.strings = "")
```


### Survival models for positive interactions

```{r}
pos.plotlist = get_surv_plotlist(positive.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE )

pdf(file.path(fig.dir, "PCAWG_positive_interactions_survivals_totmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()


pos.plotlist = get_surv_plotlist(positive.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                                 binary.status = FALSE )

pdf(file.path(fig.dir, "PCAWG_positive_interactions_survivals_nontotmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()


pos.plotlist = get_surv_plotlist(positive.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = TRUE )

pdf(file.path(fig.dir, "PCAWG_positive_interactions_survivals_totmut_binary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()
```

```{r}
pos.coxlist = get_surv_coxlist(positive.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                               tmb.logged = TRUE,
                                 binary.status = FALSE )
saveRDS(pos.coxlist, file = file.path(out.dir, "pos.coxlist.totmut.nonbinary.RDS"))


pos.coxlist = get_surv_coxlist(positive.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                               tmb.logged = TRUE,
                                 binary.status = FALSE )
saveRDS(pos.coxlist, file = file.path(out.dir, "pos.coxlist.nototmut.nonbinary.RDS"))
```


```{r}
pos.picked.models = get_surv_best_model(positive.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 param.list = list(
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(TRUE, FALSE) ),
                                 min.sample.fraction = 0.2)
saveRDS(pos.picked.models, file = file.path(out.dir, "pcawg.pos.sig.path.picked.models.RDS"))
```

### Survival models for negative interactions

```{r}
neg.plotlist = get_surv_plotlist(negative.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE )

pdf(file.path(fig.dir, "PCAWG_negative_interactions_survivals_totmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()


neg.plotlist = get_surv_plotlist(negative.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                                 binary.status = FALSE )

pdf(file.path(fig.dir, "PCAWG_negative_interactions_survivals_nontotmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()


neg.plotlist = get_surv_plotlist(negative.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = TRUE )

pdf(file.path(fig.dir, "PCAWG_negative_interactions_survivals_totmut_binary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()
```


```{r}
neg.coxlist = get_surv_coxlist(negative.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = TRUE, 
                               tmb.logged = TRUE,
                                 binary.status = FALSE )
saveRDS(neg.coxlist, file = file.path(out.dir, "neg.coxlist.totmut.nonbinary.RDS"))


neg.coxlist = get_surv_coxlist(negative.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 with.total.muts = FALSE, 
                               tmb.logged = TRUE,
                                 binary.status = FALSE )
saveRDS(neg.coxlist, file = file.path(out.dir, "neg.coxlist.nototmut.nonbinary.RDS"))
```


```{r}
neg.picked.models = get_surv_best_model(negative.sig.pathway, 
                                 dataset = PCAWG.path.sig.aggregate,
                                 clin.df = PCAWG.clin.df,
                                 param.list = list(
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(TRUE, FALSE) ),
                                 min.sample.fraction = 0.2)
saveRDS(neg.picked.models, file = file.path(out.dir, "pcawg.neg.sig.path.picked.models.RDS"))
```


### Melanoma survival for the two classes

```{r}
tissue = "Skin_Melanoma"
skin.annotated.heatmap = pathways_signatures_heatmap(
        tissue = tissue,
        signatures = PCAWG.full.subset.ann.pathways, border_color = NA,
        pathways = PCAWG.pathways.tissues, main = paste0(tissue, " - PCAWG")) %>% 
    add_pheatmap_legend_title
    
```
```{r}
skin.sigs = PCAWG.full.subset.ann.pathways %>% filter(Cancer.Types == "Skin_Melanoma")
skin.sigs$TMB = rowSums(skin.sigs[4:ncol(skin.sigs)])
rownames(skin.sigs) = substr(skin.sigs$Sample.Names, 1, 12)
skin.clin = PCAWG.clin.df %>% filter(icgc_donor_id %in% 
                                           rownames(skin.sigs)) %>% unique()
rownames(skin.clin) = skin.clin$icgc_donor_id
skin.clin = skin.clin[rownames(skin.sigs),]


skin.combined = cbind(skin.sigs, skin.clin)

skin.combined = skin.combined %>% mutate(status = ifelse(
    UV > 0 & APOBEC == 0, "UV-high", "UV-low")) 


skin.surv = survfit(Surv(survival_time, vital_status) ~ status, data = skin.combined)


P = ggsurvplot(skin.surv, data = skin.combined,
                       font.legend = c(14, "plain", "black"),
                       legend.title = element_blank(),
                       legend.labs = gsub("status=", "", names(skin.surv$strata)),
                       # palette = "jco",
                       xlab = "Days",
                       conf.int = FALSE) + 
            guides(colour = guide_legend(nrow = length(skin.surv$strata)))
        
P$plot = P$plot + theme(legend.background = element_rect(fill='transparent'),
                        legend.box.background = element_rect(fill='transparent', size = 0))

ggsave(filename = file.path(fig.dir, "PCAWG.skin.MMR_SBS17.APOBEC_SBS40.Others.survival.pdf"),
                            width = 4, height = 3)

skin.cox <- coxph(Surv(survival_time, vital_status) ~ age_at_diagnosis + 
                                 status + TMB, 
                             data = skin.combined, na.action = na.omit)

skin.cox.adjusted = ggadjustedcurves(skin.cox, 
                 variable = "status", 
                 data = skin.combined)

```

