---
title: "Signature-signature interaction null model"
author: "Anna Hakobyan"
date: "2023-11-13"
output: html_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, include = FALSE, message = FALSE)
```

```{r load-packages, message=FALSE}
library(here)
fig.dir = here("figures/sig_sig_interactions/null_model")

if(! file.exists(fig.dir)){
    dir.create(fig.dir, recursive = TRUE)
}

source(here("R/load_packages.R"))
library(igraph)
library(tidygraph)
library(pheatmap)

# data.out.dir = here("data/RDS/PCAWG", "sig_sig_ints")

# output.dir = here("output/sig_sig_int_motifs")
```


```{r}
PCAWG.full.subset.ann = readRDS(here("data", "RDS", "PCAWG", "signatures",
                                     "PCAWG.full.subset.ann.RDS"))
PCAWG.tissues = PCAWG.full.subset.ann %>% pull(Cancer.Types) %>% unique()
PCAWG.tissue.counts = PCAWG.full.subset.ann %>% pull(Cancer.Types) %>% table() %>% 
    sort(decreasing = TRUE)


TCGA.full.subset.ann = readRDS(here("data", "RDS", "TCGA", "signatures",
                                     "TCGA.full.subset.ann.RDS"))
TCGA.tissues = TCGA.full.subset.ann %>% pull(Cancer.Types) %>% unique()
TCGA.tissue.counts = TCGA.full.subset.ann %>% pull(Cancer.Types) %>% table() %>% 
    sort(decreasing = TRUE)
```

## Functions for calculating interaction metrics

```{r functions}
metric_functions = list(CoDa = cor_coda,
                        cooccurrence = cooccurrence,
                        MI = bcmi,
                        Spearman = function(x) {cor_sigs(x, method = "spearman")})

shuffle_df = function(df) {
    sapply(df, sample)   
}

get_boot_metrics = function(fun, dt) {
    replicate(1000, expr = { x = fun( shuffle_df(dt) ) ;
    x[upper.tri(x, diag = FALSE)]} )
}

shuffle_qunatiles_plot = function(tissue, dataset, quantiles, metric_functions) {
    
    tissue_set = subset_tissue(dataset, tissue = tissue) %>% 
        select(4:ncol(.))

    shuffled_metrics = lapply(metric_functions, function(x)
        get_boot_metrics(x, tissue_set) )

    plotlist = lapply(names(shuffled_metrics), function(x) {
        metric = shuffled_metrics[[x]] %>% 
            as.numeric() %>% 
            quantile(probs = quantiles)
        
        p = cbind(quantiles, metric) %>% 
            as.data.frame() %>% 
            ggplot(aes(x = quantiles, y = metric)) + 
            geom_line() + 
            geom_point() + ggtitle(x) +theme_classic() 
    })
    
    pp = ggarrange(plotlist = plotlist)
    
    pp = annotate_figure(pp, top = text_grob(tissue, 
                    size = 14))
    return(list(pp = pp, metrics = shuffled_metrics))
}
```


```{r, warning=FALSE}
quantiles = seq(0, 1, 0.01)
liver_shuffle_out = shuffle_qunatiles_plot(PCAWG.tissue.counts[1] %>% names, 
                                           quantiles = quantiles,
                                           metric_functions = metric_functions )

ggsave(liver_shuffle_out$pp, filename = file.path(fig.dir, 'liver_shuffle_metric_outs.pdf'),
       width = 5, height = 5)
```


```{r}
prost_shuffle_out = shuffle_qunatiles_plot(PCAWG.tissue.counts[2] %>% names, 
                                           quantiles = quantiles,
                                           metric_functions = metric_functions )

ggsave(prost_shuffle_out$pp, filename = file.path(fig.dir, 'prost_shuffle_metric_outs.pdf'),
       width = 5, height = 5)
```

### PCAWG distributions

```{r}
quantiles = seq(0, 1, 0.01)
PCAWG.MI.list = list()
for (tissue in names(PCAWG.tissue.counts )) {
    PCAWG.MI.list[[tissue]] = shuffle_qunatiles_plot(
        tissue, 
        PCAWG.full.subset.ann,
        quantiles = quantiles,
        metric_functions = list(MI = metric_functions$MI) )
}

MI.quantiles = do.call(c, lapply(PCAWG.MI.list, function(x) x$metrics$MI)) %>% as.numeric() %>% 
            quantile(probs = quantiles)

PCAWG.MI.quantiles = lapply(PCAWG.MI.list, function(x) x$metrics$MI %>% as.numeric() %>% 
            quantile(probs = quantiles) ) 

pcawg.98.quantile = sapply(PCAWG.MI.quantiles, function(x) unname(x[99] )) 

pcawg.df= data.frame(tissue = names(PCAWG.tissue.counts),
            tissue.counts = PCAWG.tissue.counts[names(PCAWG.tissue.counts)] %>% as.numeric(),
           quantiles.98 = pcawg.98.quantile[names(PCAWG.tissue.counts)])

pcawg.df %>%
    ggplot(aes(x = tissue, y = quantiles.98, color = tissue.counts)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90))

```

```{r}
quantiles = seq(0, 1, 0.01)
PCAWG.CoDa.list = list()
for (tissue in names(PCAWG.tissue.counts )) {
    PCAWG.CoDa.list[[tissue]] = shuffle_qunatiles_plot(
        tissue, 
        PCAWG.full.subset.ann,
        quantiles = quantiles,
        metric_functions = list(CoDa = metric_functions$CoDa) )
}

CoDa.quantiles = do.call(c, lapply(PCAWG.CoDa.list, function(x) x$metrics$CoDa)) %>% as.numeric() %>% 
            quantile(probs = quantiles)
```


```{r}
quantiles = seq(0, 1, 0.01)
PCAWG.cooc.list = list()
for (tissue in names(PCAWG.tissue.counts )) {
    PCAWG.cooc.list[[tissue]] = shuffle_qunatiles_plot(
        tissue, 
        PCAWG.full.subset.ann,
        quantiles = quantiles,
        metric_functions = list(cooc = metric_functions$cooccurrence) )
}

cooc.quantiles = do.call(c, lapply(PCAWG.cooc.list, function(x) x$metrics$cooc)) %>% as.numeric() %>% 
            quantile(probs = quantiles)
```


```{r}
quantiles = seq(0, 1, 0.01)
PCAWG.Spearman.list = list()
for (tissue in names(PCAWG.tissue.counts )) {
    PCAWG.Spearman.list[[tissue]] = shuffle_qunatiles_plot(
        tissue, 
        PCAWG.full.subset.ann,
        quantiles = quantiles,
        metric_functions = list(Spearman = metric_functions$Spearman) )
}

Spearman.quantiles = do.call(c, lapply(PCAWG.Spearman.list, function(x) x$metrics$Spearman)) %>% as.numeric() %>% 
            quantile(probs = quantiles)
```


### TCGA distributions

```{r}
quantiles = seq(0, 1, 0.01)
TCGA.MI.list = list()
for (tissue in names(TCGA.tissue.counts )) {
    TCGA.MI.list[[tissue]] = shuffle_qunatiles_plot(
        tissue, 
        TCGA.full.subset.ann,
        quantiles = quantiles,
        metric_functions = list(MI = metric_functions$MI) )
}

MI.quantiles = do.call(c, lapply(TCGA.MI.list, function(x) x$metrics$MI)) %>% as.numeric() %>% 
            quantile(probs = quantiles)
```

```{r}
quantiles = seq(0, 1, 0.01)
TCGA.CoDa.list = list()
for (tissue in names(TCGA.tissue.counts )) {
    TCGA.CoDa.list[[tissue]] = shuffle_qunatiles_plot(
        tissue, 
        TCGA.full.subset.ann,
        quantiles = quantiles,
        metric_functions = list(CoDa = metric_functions$CoDa) )
}

CoDa.quantiles = do.call(c, lapply(TCGA.CoDa.list, function(x) x$metrics$CoDa)) %>% as.numeric() %>% 
            quantile(probs = quantiles)
```


```{r}
quantiles = seq(0, 1, 0.01)
TCGA.cooc.list = list()
for (tissue in names(TCGA.tissue.counts )) {
    TCGA.cooc.list[[tissue]] = shuffle_qunatiles_plot(
        tissue, 
        TCGA.full.subset.ann,
        quantiles = quantiles,
        metric_functions = list(cooc = metric_functions$cooccurrence) )
}

cooc.quantiles = do.call(c, lapply(TCGA.cooc.list, function(x) x$metrics$cooc)) %>% as.numeric() %>% 
            quantile(probs = quantiles)
```


```{r}
quantiles = seq(0, 1, 0.01)
TCGA.Spearman.list = list()
for (tissue in names(TCGA.tissue.counts )) {
    TCGA.Spearman.list[[tissue]] = shuffle_qunatiles_plot(
        tissue, 
        TCGA.full.subset.ann,
        quantiles = quantiles,
        metric_functions = list(Spearman = metric_functions$Spearman) )
}

Spearman.quantiles = do.call(c, lapply(TCGA.Spearman.list, function(x) x$metrics$Spearman)) %>% as.numeric() %>% 
            quantile(probs = quantiles)
```
