---
title: "Checking SBS40 clonality"
author: "Anna Hakobyan"
date: "2023-10-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


``` {r load, include=FALSE}
library(here)
library(survival)
library(survminer)
source(here("R/load_packages.R"))
library(gridExtra)
library(ggforestplot)

fig.dir = here("figures/clonality")

if(!dir.exists(fig.dir)) {
    dir.create(fig.dir)
}
```

```{r}
source(here("R/process_sigs_PCAWG.R"))
```

```{r}
signature.clonality = read.delim(here("data/evolution_and_heterogeneity/2018-07-25-allSignatureChanges.tsv"))
sample.names = signature.clonality$samplename %>% unique()

columns.to.add = c("icgc_donor_id")

clonality = signature.clonality %>%
  left_join(PCAWG.sample.sheet %>% select("icgc_donor_id", "aliquot_id"), 
            by = c("samplename" = "aliquot_id")) %>% # Merge data frames 
    left_join(PCAWG.full.subset %>% select("Cancer.Types", "Sample.Names"),
              by = c("icgc_donor_id" = "Sample.Names")) %>% 
    filter(! is.na(Cancer.Types ))
```


```{r}
SBS40.clonality = clonality %>% 
    filter(signature == "SBS40") %>% 
    select(wt_clonal, wt_early, Cancer.Types) %>% 
    pivot_longer(cols = wt_clonal:wt_early, names_to = "clonality", values_to = "level") %>% 
    ggplot(aes(x = Cancer.Types, y = level, color = clonality)) +
        geom_boxplot(width = 0.4, outlier.size = 0) + 
        geom_point(position=position_jitterdodge(jitter.width = 0.2, dodge.width = 0.4), size = 0.1) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5), axis.title = element_blank()) +
    ggtitle("SBS40 clonality")

SBS5.clonality = clonality %>% 
    filter(signature == "SBS5") %>% 
    select(wt_clonal, wt_early, Cancer.Types) %>% 
    pivot_longer(cols = wt_clonal:wt_early, names_to = "clonality", values_to = "level") %>% 
    ggplot(aes(x = Cancer.Types, y = level, color = clonality)) +
        geom_boxplot(width = 0.4, outlier.size = 0) + 
        geom_point(position=position_jitterdodge(jitter.width = 0.2, dodge.width = 0.4), size = 0.1) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5), axis.title = element_blank()) 

ggarrange(SBS40.clonality, SBS5.clonality, nrow = 2)

```


```{r}
sbs40.lf = clonality %>% filter(signature  == "SBS40") %>% 
    ggplot(aes(x = Cancer.Types, y = log2fc_clonalSubclonal)) +
    geom_boxplot(outlier.size = 0) + geom_jitter(size = 0.1) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5), axis.title = element_blank()) 

sbs5.lf = clonality %>% filter(signature  == "SBS5") %>% 
    ggplot(aes(x = Cancer.Types, y = log2fc_clonalSubclonal)) +
    geom_boxplot(outlier.size = 0) + geom_jitter(size = 0.1) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5), axis.title = element_blank()) 

ggarrange(sbs40.lf, sbs5.lf, nrow = 2)

```

```{r}
sbs5vs40.lfc = clonality %>% filter(signature  %in% c("SBS5", "SBS40") ) %>% 
    mutate(signature = factor(signature, levels = c("SBS5", "SBS40"))) %>% 
    ggplot(aes(x = Cancer.Types, y = log2fc_clonalSubclonal, color = signature)) +
    geom_boxplot(outlier.size = 0, width = 0.4) + 
    geom_point(position=position_jitterdodge(jitter.width = 0.2, dodge.width = 0.4), size = 0.1) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5), axis.title = element_blank()) 
```

```{r}
dd = clonality %>% filter(signature  %in% c("SBS5", "SBS40") ) %>% 
    mutate(signature = factor(signature, levels = c("SBS5", "SBS40"))) 

bs5vs40.lfc = ggboxplot(data = dd, x = "Cancer.Types", y = "log2fc_clonalSubclonal",
          color = "signature", palette = "aaas", add = "jitter", add_params = list(size = 0.1))+
  stat_compare_means(aes(group = signature), label = "p.signif", size = 3) +
    geom_hline(yintercept = 0) + ylab("log2fc_clonalSubclonal") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5), axis.title.x = element_blank())  

ph = bs5vs40.lfc$layers[[1]]
bs5vs40.lfc$layers[[1]] = bs5vs40.lfc$layers[[4]]
bs5vs40.lfc$layers[[4]] = ph
bs5vs40.lfc

ggsave(filename = file.path(fig.dir, "sbs5_vs_sbs40.pdf"), 
       plot = bs5vs40.lfc, width = 8, height = 6)
```

