---
title: "Survival summaries"
author: "Anna Hakobyan"
date: "2022-11-20"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```



```{r load-packages, include = FALSE}
library(here)
library(survival)
library(survminer)

source(here("R/load_packages.R"))
library(gridExtra)
library(ggforestplot)

fig.dir = here("figures/survival_summaries")

```


```{r}
pcawg.sig.sig.pos = readRDS(here("data/RDS/PCAWG/sig_sig_survivals/pcawg.pos.sig.sig.picked.models.epi.nonfilter.RDS"))
pcawg.sig.sig.neg = readRDS(here("data/RDS/PCAWG/sig_sig_survivals/pcawg.neg.sig.sig.picked.models.epi.nonfilter.RDS"))

tcga.sig.sig.pos = readRDS(here("data/RDS/TCGA/sig_sig_survivals/tcga.pos.sig.sig.picked.models.epi.nonfilter.RDS"))
tcga.sig.sig.neg = readRDS(here("data/RDS/TCGA/sig_sig_survivals/tcga.neg.sig.sig.picked.models.epi.nonfilter.RDS"))

pcawg.sig.path.pos = readRDS(here("data/RDS/PCAWG/sig_pathway_survivals/pcawg.pos.sig.path.picked.models.epi.nonfilter.RDS"))
pcawg.sig.path.neg = readRDS(here("data/RDS/PCAWG/sig_pathway_survivals/pcawg.neg.sig.path.picked.models.epi.nonfilter.RDS"))

tcga.sig.path.pos = readRDS(here("data/RDS/TCGA/sig_pathway_survivals/tcga.pos.sig.path.picked.models.epi.nonfilter.RDS"))
tcga.sig.path.neg = readRDS(here("data/RDS/TCGA/sig_pathway_survivals/tcga.neg.sig.path.picked.models.epi.nonfilter.RDS"))


# pcawg.sig.sig.pos = readRDS(here("data/RDS/PCAWG/sig_sig_survivals/pos.coxlist.nototmut.nonbinary.RDS"))
# pcawg.sig.sig.neg = readRDS(here("data/RDS/PCAWG/sig_sig_survivals/neg.coxlist.nototmut.nonbinary.RDS"))
# 
# tcga.sig.sig.pos = readRDS(here("data/RDS/TCGA/sig_sig_survivals/pos.coxlist.nototmut.nonbinary.RDS"))
# tcga.sig.sig.neg = readRDS(here("data/RDS/TCGA/sig_sig_survivals/neg.coxlist.nototmut.nonbinary.RDS"))
# 
# pcawg.sig.path.pos = readRDS(here("data/RDS/PCAWG/sig_pathway_survivals/pos.coxlist.nototmut.nonbinary.RDS"))
# pcawg.sig.path.neg = readRDS(here("data/RDS/PCAWG/sig_pathway_survivals/neg.coxlist.nototmut.nonbinary.RDS"))
# 
# tcga.sig.path.pos = readRDS(here("data/RDS/TCGA/sig_pathway_survivals/pos.coxlist.nototmut.nonbinary.RDS"))
# tcga.sig.path.neg = readRDS(here("data/RDS/TCGA/sig_pathway_survivals/neg.coxlist.nototmut.nonbinary.RDS"))
```

### Forest plot for HR for tissues - Age and TMB

```{r}
pcawg.pos.sig.sig.HRs.all = HR_summary_for_all(pcawg.sig.sig.pos, type = "pos")
pcawg.neg.sig.sig.HRs.all = HR_summary_for_all(pcawg.sig.sig.neg, type = "neg")

pcawg.pos.sig.path.HRs.all = HR_summary_for_all(pcawg.sig.path.pos, type = "pos")
pcawg.neg.sig.path.HRs.all = HR_summary_for_all(pcawg.sig.path.neg, type = "neg")

tcga.pos.sig.sig.HRs.all = HR_summary_for_all(tcga.sig.sig.pos, type = "pos")
tcga.neg.sig.sig.HRs.all = HR_summary_for_all(tcga.sig.sig.neg, type = "neg")

tcga.pos.sig.path.HRs.all = HR_summary_for_all(tcga.sig.path.pos, type = "pos")
tcga.neg.sig.path.HRs.all = HR_summary_for_all(tcga.sig.path.neg, type = "neg")
```


```{r}
# HR.all.vars = list(pcawg.pos.sig.sig.HRs.all = pcawg.pos.sig.sig.HRs.all, 
#                    pcawg.neg.sig.sig.HRs.all = pcawg.neg.sig.sig.HRs.all,
#                      pcawg.pos.sig.path.HRs.all = pcawg.pos.sig.path.HRs.all, 
#                      pcawg.neg.sig.path.HRs.all = pcawg.neg.sig.path.HRs.all, 
#                      tcga.pos.sig.sig.HRs.all = tcga.pos.sig.sig.HRs.all,
#                      tcga.neg.sig.sig.HRs.all = tcga.neg.sig.sig.HRs.all, 
#                      tcga.pos.sig.path.HRs.all = tcga.pos.sig.path.HRs.all, 
#                      tcga.neg.sig.path.HRs.all = tcga.neg.sig.path.HRs.all)
# 
# HR.all.vars.total.plots = list()
# # 
# for (var in names(HR.all.vars)) {
#     HR.all.vars.total.plots[[var]] = HR.all.vars[[var]]  %>%
#         filter(P.val < 0.05) %>%
#    ggplot(aes(y = params, x = estimate, color = tissue)) +
#     geom_hline(aes(yintercept = params), alpha = 0.1) +
#       theme_classic(base_size = 15) +
#     geom_point(position=position_dodge(0.7), shape = 15, size = 3) +
#     geom_errorbar(aes(y = params, xmin = lower.95, xmax = upper.95),
#                   width=.2,
#                   position=position_dodge(0.7)) +
#     scale_y_discrete(position = "right") +
#     geom_vline(xintercept = 1, linetype="dashed", color = "gray") +
#     # coord_cartesian(xlim = c(-1, 20)) +
# 
#   theme(axis.line.y = element_blank(),
#         axis.ticks.y = element_blank()) + ggtitle(var)
# }


# for (var in names(HR.all.vars)) {
#     HR.all.vars.total.plots[[var]] = HR.all.vars[[var]]  %>% drop_na() %>%
#         filter(P.val < 0.05) %>%
#    ggplot(aes(y = params, x = log(estimate), color = tissue)) +
#     geom_hline(aes(yintercept = params), alpha = 0.1) +
#       theme_classic(base_size = 15) +
#     geom_point(position=position_dodge(0.7), shape = 15, size = 3) +
#     geom_errorbar(aes(y = params, xmin = log(lower.95), xmax = log(upper.95)),
#                   width=.2,
#                   position=position_dodge(0.7)) +
#     scale_y_discrete(position = "right") +
#     geom_vline(xintercept = 0, linetype="dashed", color = "gray") +
#     # coord_cartesian(xlim = c(-1, 20)) +
# 
#   theme(axis.line.y = element_blank(),
#         axis.ticks.y = element_blank()) + ggtitle(var)
# }
# 
# pdf(file.path(fig.dir, "logHR.all.survival.summaries.raw.pdf"),
#     width = 7, height = 3.5)
# for (var in names(HR.all.vars.total.plots)) {
#     print (HR.all.vars.total.plots[[var]])
# }
# dev.off()



# for (var in names(HR.all.vars)) {
#     HR.all.vars.total.plots[[var]] = HR.all.vars[[var]]  %>% drop_na() %>%
#         filter(P.val < 0.05) %>%
#         filter(! params %in% c("age_at_diagnosis", "log(total_muts + 1)")) %>%
#    ggplot(aes(y = params, x = log(estimate), color = tissue)) +
#     geom_hline(aes(yintercept = params), alpha = 0.1) +
#       theme_classic(base_size = 15) +
#     geom_point(position=position_dodge(0.7), shape = 15, size = 3) +
#     geom_errorbar(aes(y = params, xmin = log(lower.95), xmax = log(upper.95)),
#                   width=.2,
#                   position=position_dodge(0.7)) +
#     scale_y_discrete(position = "right") +
#     geom_vline(xintercept = 0, linetype="dashed", color = "gray") +
#         xlab("log(HR)") +
#     # coord_cartesian(xlim = c(-1, 20)) +
# 
#   theme(axis.line.y = element_blank(),
#         axis.ticks.y = element_blank()) + ggtitle(var)
# }
# 
# pdf(file.path(fig.dir, "logHR.subset.survival.summaries.raw.pdf"),
#     width = 7, height = 3.5)
# for (var in names(HR.all.vars.total.plots)) {
#     print (HR.all.vars.total.plots[[var]])
# }
# dev.off()


```

## PCAWG
#### PCAWG sig-sig interactions

```{r}
# pcawg.sig.sig.comb = rbind (pcawg.pos.sig.sig.HRs.all, pcawg.neg.sig.sig.HRs.all)
# 
pcawg.all.comb = rbind (pcawg.pos.sig.sig.HRs.all, pcawg.neg.sig.sig.HRs.all,
                            pcawg.pos.sig.path.HRs.all, pcawg.neg.sig.path.HRs.all)
pcawg.all.comb$data = "PCAWG"

# 
# p = plot_param_piechart(pcawg.all.comb, param = "log(total_muts + 1)", add.param = TRUE)
# 
# ggsave(plot = p, filename = file.path(fig.dir, "pcawg.sig.sig.tmb.piechart.pdf"),
#        width = 3, height = 1.5)
```

<!-- ### Exploring the added parameters and their relations to the rest of the estimates -->

<!-- ```{r} -->
<!-- pcawg.all.comb = rbind (pcawg.pos.sig.sig.HRs.all, pcawg.neg.sig.sig.HRs.all, -->
<!--                             pcawg.pos.sig.path.HRs.all, pcawg.pos.sig.path.HRs.all) -->

<!-- add_param_row = function(drun, orig.data, param) { -->

<!--     out = do.call(rbind, lapply(unique(drun$cond), function(cc) { -->
<!--       orig.data %>% filter(cond == cc) %>% -->
<!--         mutate(estimate = 0, lower.95 = 0, upper.95 = 0, P.val = 1, -->
<!--                params = param, sig.star = " ") %>% -->
<!--         unique () -->
<!--     } ) ) -->
<!--     row.names(out) = NULL -->
<!--     return(out) -->
<!--   } -->

<!-- pcawg.TMB.explore = pcawg.all.comb %>% -->
<!--     group_by(cond) %>% -->
<!--     summarise(non.param = all(params != "log(total_muts + 1)")) %>% -->
<!--     filter(non.param) %>% -->
<!--     ungroup() %>% -->
<!--     do(add_param_row(., pcawg.all.comb, "log(total_muts + 1)")) %>% -->
<!--     bind_rows(pcawg.all.comb, .) %>% -->
<!--     arrange(cond, params) -->


<!-- ``` -->


```{r}
# p = plot_param_piechart(pcawg.all.comb, param = "age_at_diagnosis", add.param = TRUE)
# 
# ggsave(plot = p, filename = file.path(fig.dir, "pcawg.sig.sig.age.piechart.pdf"),
#        width = 3, height = 1.5)
```


```{r}
pcawg.age.ggforest = pcawg.all.comb %>% 
    surv_add_param_fillers (., param = "age_at_diagnosis") %>% 
    plot_HR_vars( param = "age_at_diagnosis",
             average = TRUE, no_stripes = FALSE, log.HR = TRUE) + 
    theme(axis.title.y = element_blank())


ggsave(plot = pcawg.age.ggforest, 
       filename = file.path(fig.dir, "pcawg.age.ggforest.logHR.pdf"),
       width = 4.5, height = 3)


pcawg.tmb.ggforest = pcawg.all.comb %>% 
    surv_add_param_fillers (., param = "log(total_muts + 1)") %>% 
    plot_HR_vars(param = "log(total_muts + 1)",
             average = TRUE, no_stripes = FALSE, log.HR = TRUE)

ggsave(plot = pcawg.tmb.ggforest, 
       filename = file.path(fig.dir, "pcawg.tmb.ggforest.logHR.pdf"),
       width = 4.5, height = 3)
```



```{r}
pcawg.sig.sig.comb = rbind (pcawg.pos.sig.sig.HRs.all, pcawg.neg.sig.sig.HRs.all)
pcawg.sig.sig.comb$data = "PCAWG"

pp = plot_sigint_forest(pcawg.sig.sig.comb)

ggsave(plot = pp, filename = file.path(fig.dir, "pcawg.sig.sig.significant_interaction.pdf"),
       width = 6.5, height = 1.5)
```
 
#### PCAWG sig-path interactions

```{r}
# pcawg.pos.sig.sig.HRs.all = HR_summary_for_all(pcawg.sig.sig.pos)
# pcawg.neg.sig.sig.HRs.all = HR_summary_for_all(pcawg.sig.sig.neg)

pcawg.sig.path.comb = rbind (pcawg.pos.sig.path.HRs.all, pcawg.neg.sig.path.HRs.all)

p = plot_param_piechart(pcawg.sig.path.comb, param = "age_at_diagnosis", add.param = TRUE)

ggsave(plot = p, filename = file.path(fig.dir, "pcawg.sig.path.age.piechart.pdf"),
       width = 3, height = 3)
```


```{r}
pp = plot_sigint_forest(pcawg.sig.path.comb)

ggsave(plot = pp, filename = file.path(fig.dir, "pcawg.sig.path.significant_interaction.pdf"),
       width = 7, height = 2.3)
```
 
 
## TCGA
### TCGA sig-sig interactions


```{r}
tcga.all.comb = rbind (tcga.pos.sig.sig.HRs.all, tcga.neg.sig.sig.HRs.all,
                           tcga.pos.sig.path.HRs.all, tcga.neg.sig.path.HRs.all)
tcga.all.comb$data = "TCGA"
 
p = plot_param_piechart(tcga.all.comb, param = "log(total_muts + 1)", add.param = TRUE)

ggsave(plot = p, filename = file.path(fig.dir, "tcga.sig.sig.tmb.piechart.pdf"),
       width = 3, height = 1.5)
```

```{r}
p = tcga.all.comb %>% 
    surv_add_param_fillers ( param = "age_at_diagnosis") %>% 
    plot_param_piechart(param = "age_at_diagnosis", 
                        add.param = FALSE)

ggsave(plot = p, filename = file.path(fig.dir, "tcga.sig.sig.age.piechart.pdf"),
       width = 3, height = 1.5)
```



```{r}
tcga.age.ggforest = tcga.all.comb %>% 
    surv_add_param_fillers ( param = "age_at_diagnosis") %>%
    plot_HR_vars(param = "age_at_diagnosis",
             average = TRUE, no_stripes = FALSE, log.HR = TRUE) + 
    theme(axis.title.y = element_blank())

ggsave(plot = tcga.age.ggforest, 
       filename = file.path(fig.dir, "tcga.age.ggforest.logHR.pdf"),
       width = 4.5, height = 3)


tcga.tmb.ggforest = tcga.all.comb %>% 
    surv_add_param_fillers ( param = "log(total_muts + 1)") %>%
    plot_HR_vars(param = "log(total_muts + 1)",
             average = TRUE, no_stripes = FALSE, log.HR = TRUE)

ggsave(plot = tcga.tmb.ggforest, 
       filename = file.path(fig.dir, "tcga.tmb.ggforest.logHR.pdf"),
       width = 4.5, height = 3)
```

### TCGA signature-signature interactions 

```{r}
tcga.sig.sig.comb = rbind (tcga.pos.sig.sig.HRs.all, tcga.neg.sig.sig.HRs.all)
tcga.sig.sig.comb$data = "TCGA"

pp = plot_sigint_forest(tcga.sig.sig.comb)

ggsave(plot = pp, filename = file.path(fig.dir, "tcga.sig.sig.significant_interaction.pdf"),
       width = 7, height = 2)
```
 
#### TCGA sig-path interactions

```{r}
tcga.sig.path.comb = rbind (tcga.pos.sig.path.HRs.all, tcga.neg.sig.path.HRs.all)
tcga.sig.path.comb$data = "TCGA"

pp = plot_sigint_forest(tcga.sig.path.comb)

ggsave(plot = pp, filename = file.path(fig.dir, "tcga.sig.path.significant_interaction.pdf"),
       width = 7, height = 2)
```
 
 
### Age and TMB for both datasets

```{r}
both.data.comb = rbind(pcawg.all.comb, tcga.all.comb)

p = both.data.comb %>% 
    surv_add_param_fillers(param = "age_at_diagnosis") %>% 
    plot_param_piechart(param = "age_at_diagnosis")

ggsave(plot = p, filename = file.path(fig.dir, "both.sig.sig.age.piechart.pdf"),
       width = 3, height = 1.5)

both.age.ggforest.log.HR = both.data.comb %>% 
    surv_add_param_fillers(param = "age_at_diagnosis") %>% 
    plot_HR_vars(param = "age_at_diagnosis", log.HR = TRUE,
             average = TRUE, no_stripes = FALSE)

ggsave(plot = both.age.ggforest.log.HR, 
       filename = file.path(fig.dir, "both.age.ggforest.log.HR.pdf"),
       width = 4, height = 5)


p = both.data.comb %>% 
    surv_add_param_fillers(param = "log(total_muts + 1)") %>% 
    plot_param_piechart(param = "log(total_muts + 1)", average = TRUE)

ggsave(plot = p, filename = file.path(fig.dir, "both.sig.sig.tmb.piechart.pdf"),
       width = 3, height = 1.5)


both.tmb.ggforest.log.HR =  both.data.comb %>% 
    surv_add_param_fillers(param = "log(total_muts + 1)") %>% 
    plot_HR_vars(param = "log(total_muts + 1)", log.HR = TRUE,
             average = FALSE, no_stripes = FALSE)

ggsave(plot = both.tmb.ggforest.log.HR, 
       filename = file.path(fig.dir, "both.tmb.ggforest.log.HR.pdf"),
       width = 4, height = 5)
```
 
<!-- ### PCAWG all models with significant interaction between sig-sig  -->

<!-- ```{r} -->
<!-- pcawg.pos.ss.picked.surv.out = readRDS(file = file.path(here("data/RDS/PCAWG/sig_sig_survivals"), "pcawg.pos.sig.sig.picked.models.epi.RDS")) -->

<!-- # pcawg.pos.ss.picked.surv.out = readRDS(file = file.path(here("data/RDS/PCAWG/sig_sig_survivals"), "pcawg.pos.sig.sig.picked.models.RDS")) -->

<!-- # pcawg.pos.ss.picked.models = lapply(pcawg.pos.ss.picked.surv.out, function(x) {x[["model"]]}) -->

<!-- pcawg.neg.ss.picked.surv.out = readRDS(file = file.path(here("data/RDS/PCAWG/sig_sig_survivals"), "pcawg.neg.sig.sig.picked.models.epi.RDS")) -->

<!-- # pcawg.neg.ss.picked.surv.out = readRDS(file = file.path(here("data/RDS/PCAWG/sig_sig_survivals"), "pcawg.neg.sig.sig.picked.models.RDS")) -->

<!-- # pcawg.neg.ss.picked.models = lapply(pcawg.neg.ss.picked.surv.out, function(x) {x[["model"]]}) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- pcawg.pos.ss.picked.summary = HR_summary_for_all(pcawg.pos.ss.picked.surv.out, type = "pos") -->
<!-- pcawg.neg.ss.picked.summary = HR_summary_for_all(pcawg.neg.ss.picked.surv.out, type = "neg") -->

<!-- pcawg.ss.picked.combined = rbind(pcawg.pos.ss.picked.summary, pcawg.neg.ss.picked.summary) -->

<!-- pp = plot_sigint_forest(pcawg.ss.picked.combined %>% filter(P.val < 0.05, grepl("[*+]", params), -->
<!--                                                                params != "log(total_muts + 1)")) -->

<!-- ggsave(plot = pp, filename = file.path(fig.dir, "pcawg.sig.sig.adjusted.models.significant_interaction.pdf"), -->
<!--        width = 7, height = 3) -->
<!-- ``` -->


<!-- ### PCAWG all models with significant interaction between sig-path -->


<!-- ```{r} -->
<!-- pcawg.pos.sp.picked.surv.out = readRDS(file = file.path(here("data/RDS/PCAWG/sig_pathway_survivals"), "pcawg.pos.sig.path.picked.models.epi.RDS")) -->
<!-- # pcawg.pos.ss.picked.models = lapply(pcawg.pos.ss.picked.surv.out, function(x) {x[["model"]]}) -->

<!-- pcawg.neg.sp.picked.surv.out = readRDS(file = file.path(here("data/RDS/PCAWG/sig_pathway_survivals"), "pcawg.neg.sig.path.picked.models.epi.RDS")) -->
<!-- # pcawg.neg.ss.picked.models = lapply(pcawg.neg.ss.picked.surv.out, function(x) {x[["model"]]}) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- pcawg.pos.sp.picked.summary = HR_summary_for_all(pcawg.pos.sp.picked.surv.out, type = "pos") -->

<!-- pcawg.neg.sp.picked.summary = HR_summary_for_all(pcawg.neg.sp.picked.surv.out, type = "neg") -->
<!-- # This list is empty -->

<!-- pcawg.sp.picked.combined = rbind(pcawg.pos.sp.picked.summary, pcawg.neg.sp.picked.summary) -->
<!-- # pcawg.sp.picked.combined = pcawg.pos.sp.picked.summary -->

<!-- pp = plot_sigint_forest(pcawg.sp.picked.combined) +  -->
<!--     theme(plot.margin = margin(1, 0,0,0, "cm")) -->

<!-- ggsave(plot = pp, filename = file.path(fig.dir, "pcawg.sig.path.adjusted.models.significant_interaction.pdf"), -->
<!--        width = 7, height = 2) -->
<!-- ``` -->


<!-- ### TCGA all models with significant interaction between sig-sig -->

<!-- ```{r} -->
<!-- tcga.pos.ss.picked.surv.out = readRDS(file = file.path(here("data/RDS/TCGA/sig_sig_survivals"), -->
<!--                                                        "tcga.pos.sig.sig.picked.models.epi.RDS")) -->
<!-- # tcga.pos.ss.picked.models = lapply(tcga.pos.ss.picked.surv.out, function(x) {x[["model"]]}) -->

<!-- tcga.neg.ss.picked.surv.out = readRDS(file = file.path(here("data/RDS/TCGA/sig_sig_survivals"), -->
<!--                                                        "tcga.neg.sig.sig.picked.models.epi.RDS")) -->
<!-- # tcga.neg.ss.picked.models = lapply(tcga.neg.ss.picked.surv.out, function(x) {x[["model"]]}) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- tcga.pos.ss.picked.summary = HR_summary_for_all(tcga.pos.ss.picked.surv.out, type = "pos") -->
<!-- tcga.neg.ss.picked.summary = HR_summary_for_all(tcga.neg.ss.picked.surv.out, type = "neg") -->

<!-- tcga.ss.picked.combined = rbind(tcga.pos.ss.picked.summary, tcga.neg.ss.picked.summary) -->

<!-- clock.like = c("Ageing", "SBS40", "SBS5") -->
<!-- pairs = combn(clock.like, 2) -->
<!-- pair.strings <- c(paste(pairs[1, ], pairs[2, ], sep = " + "),  -->
<!--                   paste(pairs[2, ], pairs[1, ], sep = " + ")) -->

<!-- tcga.ss.picked.combined = tcga.ss.picked.combined %>% filter(! int %in% pair.strings ) -->

<!-- pp = plot_sigint_forest(tcga.ss.picked.combined) -->

<!-- ggsave(plot = pp, filename = file.path(fig.dir, "tcga.sig.sig.adjusted.models.significant_interaction.pdf"), -->
<!--        width = 7, height = 3.2) -->
<!-- ``` -->


<!-- ### TCGA all models with significant interaction between sig-path -->

<!-- ```{r} -->
<!-- tcga.pos.sp.picked.surv.out = readRDS(file = file.path(here("data/RDS/TCGA/sig_pathway_survivals"), "tcga.pos.sig.path.picked.models.epi.RDS")) -->
<!-- # tcga.pos.ss.picked.models = lapply(tcga.pos.ss.picked.surv.out, function(x) {x[["model"]]}) -->

<!-- tcga.neg.sp.picked.surv.out = readRDS(file = file.path(here("data/RDS/TCGA/sig_pathway_survivals"), "tcga.neg.sig.path.picked.models.epi.RDS")) -->
<!-- # tcga.neg.ss.picked.models = lapply(tcga.neg.ss.picked.surv.out, function(x) {x[["model"]]}) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- tcga.pos.sp.picked.summary = HR_summary_for_all(tcga.pos.sp.picked.surv.out, type = "pos") -->

<!-- tcga.neg.sp.picked.summary = HR_summary_for_all(tcga.neg.sp.picked.surv.out, type = "neg") -->

<!-- tcga.sp.picked.combined = rbind(tcga.pos.sp.picked.summary, tcga.neg.sp.picked.summary) -->

<!-- pp = plot_sigint_forest(tcga.sp.picked.combined) -->

<!-- ggsave(plot = pp, filename = file.path(fig.dir, "tcga.sig.path.adjusted.models.significant_interaction.pdf"), -->
<!--        width = 7, height = 3.2) -->
<!-- ``` -->

### Specific interactions to be explored

```{r}
p = pcawg.sig.sig.pos$`Liver_HCC :: SBS40 + Ageing

int.oi = pcawg.sig.sig.pos[["Liver_HCC :: SBS40 + Ageing"]]
summary(int.oi$model)

int.oi = pcawg.sig.sig.pos[["Liver_HCC :: SBS40 + Ageing"]]


int.oi = pcawg.sig.sig.neg[["Liver_HCC :: SBS40 + SBS29"]]
int.forest = survminer::ggforest(model = int.oi$model, data = int.oi$survival.df)

```



### Non-epistatic interactions 

```{r}
pcawg.sig.sig.pos.nonepi = readRDS(here("data/RDS/PCAWG/sig_sig_survivals/pcawg.pos.sig.sig.picked.models.nonepi.RDS"))
pcawg.sig.sig.neg.nonepi = readRDS(here("data/RDS/PCAWG/sig_sig_survivals/pcawg.neg.sig.sig.picked.models.nonepi.RDS"))

tcga.sig.sig.pos.nonepi = readRDS(here("data/RDS/TCGA/sig_sig_survivals/tcga.pos.sig.sig.picked.models.nonepi.RDS"))
tcga.sig.sig.neg.nonepi = readRDS(here("data/RDS/TCGA/sig_sig_survivals/tcga.neg.sig.sig.picked.models.nonepi.RDS"))

pcawg.sig.path.pos.nonepi = readRDS(here("data/RDS/PCAWG/sig_pathway_survivals/pcawg.pos.sig.path.picked.models.nonepi.RDS"))
pcawg.sig.path.neg.nonepi = readRDS(here("data/RDS/PCAWG/sig_pathway_survivals/pcawg.neg.sig.path.picked.models.nonepi.RDS"))

tcga.sig.path.pos.nonepi = readRDS(here("data/RDS/TCGA/sig_pathway_survivals/tcga.pos.sig.path.picked.models.nonepi.RDS"))
tcga.sig.path.neg.nonepi = readRDS(here("data/RDS/TCGA/sig_pathway_survivals/tcga.neg.sig.path.picked.models.nonepi.RDS"))
```

```{r}
pcawg.pos.sig.sig.HRs.nonepi = HR_summary_for_all(pcawg.sig.sig.pos.nonepi, type = "pos")
pcawg.neg.sig.sig.HRs.nonepi = HR_summary_for_all(pcawg.sig.sig.neg.nonepi, type = "neg")

pcawg.pos.sig.path.HRs.nonepi = HR_summary_for_all(pcawg.sig.path.pos.nonepi, type = "pos")
# pcawg.neg.sig.path.HRs.nonepi = HR_summary_for_all(pcawg.sig.path.neg.nonepi, type = "neg")

tcga.pos.sig.sig.HRs.nonepi = HR_summary_for_all(tcga.sig.sig.pos.nonepi, type = "pos")
tcga.neg.sig.sig.HRs.nonepi = HR_summary_for_all(tcga.sig.sig.neg.nonepi, type = "neg")

tcga.pos.sig.path.HRs.nonepi = HR_summary_for_all(tcga.sig.path.pos.nonepi, type = "pos")
tcga.neg.sig.path.HRs.nonepi = HR_summary_for_all(tcga.sig.path.neg.nonepi, type = "neg")
```


```{r}
pcawg.sig.sig.nonepi = rbind (pcawg.pos.sig.sig.HRs.nonepi, pcawg.neg.sig.sig.HRs.nonepi)
pcawg.sig.sig.nonepi$data = "PCAWG"

pp = plot_sigint_forest(pcawg.sig.sig.nonepi)

ggsave(plot = pp, filename = file.path(fig.dir, "pcawg.sig.sig.significant_interaction.nonepi.pdf"),
       width = 6.5, height = 1.8)
```

```{r}
tcga.sig.sig.nonepi = rbind (tcga.pos.sig.sig.HRs.nonepi, tcga.neg.sig.sig.HRs.nonepi)
tcga.sig.sig.nonepi$data = "TCGA"

pp = plot_sigint_forest(tcga.sig.sig.nonepi)

ggsave(plot = pp, filename = file.path(fig.dir, "tcga.sig.sig.significant_interaction.nonepi.pdf"),
       width = 6.5, height = 3)
```



```{r}
pcawg.sig.path.nonepi = pcawg.pos.sig.path.HRs.nonepi
pcawg.sig.path.nonepi$data = "PCAWG"

pp = plot_sigint_forest(pcawg.sig.path.nonepi)

ggsave(plot = pp, filename = file.path(fig.dir, "pcawg.sig.path.significant_interaction.nonepi.pdf"),
       width = 6.5, height = 1.5)
```

```{r}
tcga.sig.path.nonepi = rbind (tcga.pos.sig.path.HRs.nonepi, tcga.neg.sig.path.HRs.nonepi)
tcga.sig.path.nonepi$data = "TCGA"

pp = plot_sigint_forest(tcga.sig.path.nonepi)

ggsave(plot = pp, filename = file.path(fig.dir, "tcga.sig.path.significant_interaction.nonepi.pdf"),
       width = 6.5, height = 1.8)
```