---
title: "Survival analysis of signature-signature interactions in TCGA"
output: 
  html_document:
    df_print: paged
---

```{r}
rm(list = ls())
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```

```{r load-packages, message=FALSE}
library(here)
library(survival)
library(survminer)
library(nonnestcox)

source(here("R/load_packages.R"))
library(gridExtra)

input.dir = here("data/RDS/TCGA/metadata")

out.dir = here("data/RDS/TCGA/sig_pathway_survivals")
fig.dir = here("figures/sig_pathway_survivals")

for (dir.name in c(fig.dir, out.dir)) {
    if (! file.exists(dir.name) ) {
        dir.create(dir.name, recursive = TRUE)
    }
}
```

### Reading in clinical and signature data

```{r}
TCGA.full.subset.ann.pathways = readRDS(file = here("data/RDS/TCGA/10_onco_pathways",
                                              "TCGA.full.subset.ann.pathways.RDS"))

TCGA.pathways.tissues = readRDS(file = here("data/RDS/TCGA/10_onco_pathways",
                                              "tcga_pathways.RDS"))

colnames(TCGA.pathways.tissues) = gsub("[ -]", ".", colnames(TCGA.pathways.tissues))

if (all.equal(rownames(TCGA.full.subset.ann.pathways), rownames(TCGA.pathways.tissues))) {

    TCGA.path.sig.aggregate = cbind(TCGA.full.subset.ann.pathways, 
                                     TCGA.pathways.tissues[4:ncol(TCGA.pathways.tissues)])
} else {
    stop("Rownames of pathway and signature dataframes do not match.\n")
}


TCGA.clin.df = readRDS(file = file.path(input.dir, "TCGA.clin.df.RDS") )

positive.sig.pathway = read.delim(file = here("supp_data", 
                                        "TCGA_sig_pathway_positive_interaction_tissue_summaries.tsv"),
                              row.names = 1, na.strings = "")

negative.sig.pathway = read.delim(file = here("supp_data", 
                                        "TCGA_sig_pathway_negative_interaction_tissue_summaries.tsv"),
                            row.names = 1, na.strings = "")
```


### Survival models for positive interactions

<!-- ```{r} -->
<!-- pos.plotlist = get_surv_plotlist(positive.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = TRUE,  -->
<!--                                  tmb.logged = TRUE, -->
<!--                                  binary.status = FALSE ) -->

<!-- pdf(file.path(fig.dir, "TCGA_positive_interactions_survivals_totmut_nonbinary.pdf"), -->
<!--     onefile = TRUE, width = 6, height = 8) -->

<!-- for (i in 1:length(pos.plotlist) ) { -->
<!--     try({print(pos.plotlist[[i]] ) }) -->
<!-- } -->
<!-- dev.off() -->


<!-- pos.plotlist = get_surv_plotlist(positive.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = FALSE,  -->
<!--                                  binary.status = FALSE ) -->

<!-- pdf(file.path(fig.dir, "TCGA_positive_interactions_survivals_nontotmut_nonbinary.pdf"), -->
<!--     onefile = TRUE, width = 6, height = 8) -->

<!-- for (i in 1:length(pos.plotlist) ) { -->
<!--     try({print(pos.plotlist[[i]] ) }) -->
<!-- } -->
<!-- dev.off() -->


<!-- pos.plotlist = get_surv_plotlist(positive.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = TRUE,  -->
<!--                                  tmb.logged = TRUE, -->
<!--                                  binary.status = TRUE ) -->

<!-- pdf(file.path(fig.dir, "TCGA_positive_interactions_survivals_totmut_binary.pdf"), -->
<!--     onefile = TRUE, width = 6, height = 8) -->

<!-- for (i in 1:length(pos.plotlist) ) { -->
<!--     try({print(pos.plotlist[[i]] ) }) -->
<!-- } -->
<!-- dev.off() -->
<!-- ``` -->



<!-- ```{r} -->
<!-- pos.coxlist = get_surv_coxlist(positive.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = TRUE,  -->
<!--                                  tmb.logged = TRUE, -->
<!--                                  binary.status = FALSE ) -->

<!-- saveRDS(pos.coxlist, file = file.path(out.dir, "pos.coxlist.totmut.nonbinary.RDS")) -->


<!-- pos.coxlist = get_surv_coxlist(positive.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = FALSE,  -->
<!--                                  tmb.logged = TRUE, -->
<!--                                  binary.status = FALSE ) -->

<!-- saveRDS(pos.coxlist, file = file.path(out.dir, "pos.coxlist.nototmut.nonbinary.RDS")) -->
<!-- ``` -->

```{r, include = FALSE, warning = FALSE, message = FALSE}
pos.picked.models = get_surv_best_model(positive.sig.pathway, 
                                 dataset = TCGA.path.sig.aggregate,
                                 clin.df = TCGA.clin.df,
                                 param.list = list(
                                     "age.at.diagnosis" = c(TRUE, FALSE),
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(FALSE),
                                     "epistatic" = c(TRUE, FALSE)),
                                 filename = here("supp_data/tcga_positive_sig_path_survivals.xlsx"),
                                 min.sample.fraction = 0,
                                 rm.non.sig.sheets = TRUE,
                                 return.only.sig = TRUE,
                                sig.threshold = 0.1)

saveRDS(pos.picked.models, file = file.path(out.dir, "tcga.pos.sig.path.picked.models.epi.RDS"))



pos.picked.models = get_surv_best_model(positive.sig.pathway, 
                                 dataset = TCGA.path.sig.aggregate,
                                 clin.df = TCGA.clin.df,
                                 param.list = list(
                                     "age.at.diagnosis" = c(TRUE, FALSE),
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(FALSE),
                                     "epistatic" = c(FALSE)),
                                 filename = here("supp_data/tcga_positive_sig_path_survivals_nonepi.xlsx"),
                                 min.sample.fraction = 0,
                                 rm.non.sig.sheets = TRUE,
                                 return.only.sig = TRUE,
                                 sig.threshold = 0.1)

saveRDS(pos.picked.models, file = file.path(out.dir, "tcga.pos.sig.path.picked.models.nonepi.RDS"))
```

### Survival models for negative interactions

<!-- ```{r} -->
<!-- neg.plotlist = get_surv_plotlist(sig.sig.tissues.matrix = negative.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = TRUE,  -->
<!--                                  tmb.logged = TRUE, -->
<!--                                  binary.status = FALSE ) -->

<!-- pdf(file.path(fig.dir, "TCGA_negative_interactions_survivals_totmut_nonbinary.pdf"), -->
<!--     onefile = TRUE, width = 6, height = 8) -->

<!-- for (i in 1:length(neg.plotlist) ) { -->
<!--     try({print(neg.plotlist[[i]] ) }) -->
<!-- } -->
<!-- dev.off() -->


<!-- neg.plotlist = get_surv_plotlist(negative.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = FALSE,  -->
<!--                                  binary.status = FALSE ) -->

<!-- pdf(file.path(fig.dir, "TCGA_negative_interactions_survivals_nontotmut_nonbinary.pdf"), -->
<!--     onefile = TRUE, width = 6, height = 8) -->

<!-- for (i in 1:length(neg.plotlist) ) { -->
<!--     try({print(neg.plotlist[[i]] ) }) -->
<!-- } -->
<!-- dev.off() -->


<!-- neg.plotlist = get_surv_plotlist(negative.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = TRUE,  -->
<!--                                  tmb.logged = TRUE, -->
<!--                                  binary.status = TRUE ) -->

<!-- pdf(file.path(fig.dir, "TCGA_negative_interactions_survivals_totmut_binary.pdf"), -->
<!--     onefile = TRUE, width = 6, height = 8) -->

<!-- for (i in 1:length(neg.plotlist) ) { -->
<!--     try({print(neg.plotlist[[i]] ) }) -->
<!-- } -->
<!-- dev.off() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- neg.coxlist = get_surv_coxlist(negative.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = TRUE,  -->
<!--                                  tmb.logged = TRUE, -->
<!--                                  binary.status = FALSE) -->

<!-- saveRDS(neg.coxlist, file = file.path(out.dir, "neg.coxlist.totmut.nonbinary.RDS")) -->


<!-- neg.coxlist = get_surv_coxlist(negative.sig.pathway,  -->
<!--                                  dataset = TCGA.path.sig.aggregate, -->
<!--                                  clin.df = TCGA.clin.df, -->
<!--                                  with.total.muts = FALSE,  -->
<!--                                  tmb.logged = TRUE, -->
<!--                                  binary.status = FALSE) -->

<!-- saveRDS(neg.coxlist, file = file.path(out.dir, "neg.coxlist.nototmut.nonbinary.RDS")) -->
<!-- ``` -->

```{r}
neg.picked.models = get_surv_best_model(negative.sig.pathway, 
                                 dataset = TCGA.path.sig.aggregate,
                                 clin.df = TCGA.clin.df,
                                 param.list = list(
                                     "age.at.diagnosis" = c(TRUE, FALSE),
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(FALSE),
                                     "epistatic" = c(TRUE, FALSE)),
                                 filename = here("supp_data/tcga_negative_sig_path_survivals.xlsx"),
                                 min.sample.fraction = 0,
                                 rm.non.sig.sheets = TRUE,
                                 return.only.sig = TRUE,
                                sig.threshold = 0.1)

saveRDS(neg.picked.models, file = file.path(out.dir, "tcga.neg.sig.path.picked.models.epi.RDS"))



neg.picked.models = get_surv_best_model(negative.sig.pathway, 
                                 dataset = TCGA.path.sig.aggregate,
                                 clin.df = TCGA.clin.df,
                                 param.list = list(
                                     "age.at.diagnosis" = c(TRUE, FALSE),
                                     "with.total.muts" = c(TRUE, FALSE), 
                                     "tmb.logged" = c(TRUE),
                                     "binary.status" = c(FALSE),
                                     "epistatic" = c(FALSE)),
                                 filename = here("supp_data/tcga_negative_sig_path_survivals_nonepi.xlsx"),
                                 min.sample.fraction = 0,
                                 rm.non.sig.sheets = TRUE,
                                 return.only.sig = TRUE,
                                 sig.threshold = 0.1)

saveRDS(neg.picked.models, file = file.path(out.dir, "tcga.neg.sig.path.picked.models.nonepi.RDS"))

```

### TCGA survival for specific interactions 

```{r}
stomach_MMR_HIPPO = survival_for_interactions(dataset = TCGA.path.sig.aggregate, 
                                                      signatures = c( "MMR", "HIPPO"), 
                                                      tissues = c("Stomach_AdenoCa"), 
                                                      clin.df = TCGA.clin.df,
                                                      legend_pos = c(0.9, 0.9),
                                                      with.total.muts = TRUE,
                                              tmb.logged = TRUE,
                                                      binary.status = FALSE)

stomach_MMR_HIPPO_adjusted = ggadjustedcurves(stomach_MMR_HIPPO$coxout, 
                 variable = "status", 
                 data = stomach_MMR_HIPPO$survival.df)


ggsave(plot = stomach_MMR_HIPPO_adjusted + 
           theme(plot.margin = unit(c(0, 1.5, 0,0), units = "cm"),
                 legend.title = element_blank()),
       filename = file.path(fig.dir, "TCGA_stomach_MMR_HIPPO_adjusted.survivals.pdf"),
       width = 4, height = 2.5)



uterus_MMR_HIPPO = survival_for_interactions(dataset = TCGA.path.sig.aggregate, 
                                                      signatures = c( "MMR", "HIPPO"), 
                                                      tissues = c("Uterus_AdenoCa"), 
                                                      clin.df = TCGA.clin.df,
                                                      legend_pos = c(0.9, 0.9),
                                                      with.total.muts = TRUE,
                                              tmb.logged = TRUE,
                                                      binary.status = FALSE)

uterus_MMR_HIPPO_adjusted = ggadjustedcurves(stomach_MMR_HIPPO$coxout, 
                 variable = "status", 
                 data = uterus_MMR_HIPPO$survival.df)


ggsave(plot = uterus_MMR_HIPPO_adjusted + 
           theme(plot.margin = unit(c(0, 1.5, 0,0), units = "cm"),
                 legend.title = element_blank()),
       filename = file.path(fig.dir, "TCGA_uterus_MMR_HIPPO_adjusted.survivals.pdf"),
       width = 4, height = 2.5)
```


```{r}
uterus_stomach_MMR_HIPPO = survival_for_interactions(dataset = TCGA.path.sig.aggregate, 
                                                      signatures = c( "MMR", "HIPPO"), 
                                                      tissues = c("Stomach_AdenoCa", "Uterus_AdenoCa"), 
                                                      clin.df = TCGA.clin.df,
                                                      legend_pos = c(0.9, 0.9),
                                                      with.total.muts = TRUE,
                                              tmb.logged = TRUE,
                                                      binary.status = FALSE)


uterus_MMR_HIPPO_adjusted = ggadjustedcurves(stomach_MMR_HIPPO$coxout, 
                 variable = "status", 
                 data = uterus_MMR_HIPPO$survival.df)


ggsave(plot = uterus_MMR_HIPPO_adjusted + theme(plot.margin = unit(c(0, 1.5, 0,0), units = "cm") ),
       filename = file.path(fig.dir, "TCGA_uterus_stomach_MMR_HIPPO.adjusted.survivals.pdf"),
       width = 4, height = 3.5)



uterus_stomach_MMR_HIPPO_ggforest = ggforest(model = uterus_stomach_MMR_HIPPO$coxout, 
                                             data = uterus_stomach_MMR_HIPPO$survival.df)


ggsave(plot = uterus_stomach_MMR_HIPPO_ggforest,
       filename = file.path(fig.dir, "TCGA_uterus_stomach_MMR_HIPPO.ggforest.pdf"),
       width = 6, height = 2.9)
```

