---
title: "Immune states in TCGA"
output:
  html_document:
    df_print: paged
---

```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 5, echo = FALSE, 
                      warning = FALSE, message = FALSE)
```


```{r load-packages}
library(here)
fig.dir = here("figures/immune_analysis")


for (dir.path in c(fig.dir, file.path( fig.dir, 
                                  "immune_to_signature", "by_tissues", "oddsratio"))) {
    if(! file.exists(dir.path)){
        dir.create(dir.path, recursive = TRUE)
    }   
}


source(here("R/load_packages.R"))

out.dir = here("data/RDS/TCGA/immune_states")
```


```{r}
TCGA.full.subset.ann = readRDS(here("data", "RDS", "TCGA", "signatures",
                                     "TCGA.full.subset.ann.RDS"))

immune.subtypes.all = readxl::read_excel(here("data/raw/TCGA/immune_states/1-s2.0-S1074761318301213-mmc2.xlsx"))


TCGA.samplenames = gsub("(TCGA-..-....)-.*$", "\\1", TCGA.full.subset.ann$Sample.Names)

matches = match(TCGA.samplenames, immune.subtypes.all$`TCGA Participant Barcode`)

immune.subtypes = immune.subtypes.all[ matches, ]


mapping.immune.subtypes = setNames(c("Wound healing", 
                              expression(paste("IFN-", gamma, " dominant")),
                              "Inflammatory",
                              "Lymphocyte depleted",
                              "Imm. quiet",
                              expression(paste("TGF-", beta, " dominant"))), paste0("C", 1:6))

mapping.immune.subtypes = setNames(c("Wound healing", 
                                     'IFN-\u03B3 dominant',
                                     "Inflammatory",
                                     "Lymph. depleted",
                                     "Imm. quiet",
                                     'TGF-\u03B2 dominant'), paste0("C", 1:6))

tcga.immune.states = cbind(TCGA.full.subset.ann,
                              immune.subtypes$`Immune Subtype`)

colnames(tcga.immune.states)[ncol(tcga.immune.states)] = "Immune.Subtype"
```



```{r}
tcga.immune.summaries.gg = tcga.immune.states %>% 
    group_by(Cancer.Types, Immune.Subtype) %>% 
    count( Cancer.Types, Immune.Subtype, name = "total") %>% ungroup() %>% 
    tidyr::complete(Cancer.Types, Immune.Subtype, fill = list(total = 0))

immune.class.mapping = c("C1" = "Wound healing",
                         "C2" = "INF-\u03B3 dominant",
                         "C3" = "Inflammatory",
                         "C4" = "Lymphocyte depleted",
                         "C5" = "Immunologically quiet",
                         "C6" = "TGF-\u03B2 dominant",
                         "CNA" = "CNA")

tcga.immune.summaries.gg$Immune.type = immune.class.mapping[tcga.immune.summaries.gg$Immune.Subtype]
tcga.immune.summaries.gg$Immune.type = factor(tcga.immune.summaries.gg$Immune.type,
                                               # levels = c("CNA", "TGF-β dominant",
                                               #            "Immunologically quiet",
                                               #            "Lymphocyte depleted",
                                               #            "Inflammatory",
                                               #            "INF-γ dominant",
                                               #            "Wound healing")
                                               levels = c("Wound healing", "INF-γ dominant",
                                                          "Inflammatory", "Lymphocyte depleted",
                                                          "Immunologically quiet", "TGF-β dominant",
                                                          "CNA"))

tcga.immune.states.plot = tcga.immune.summaries.gg %>% 
    rename(Counts = total) %>% 
    # mutate(Pathway = factor(Pathway, levels = path.order)) %>% 
    
    ggplot(aes(x = Immune.type, y = Cancer.Types) ) + 
        geom_tile(aes(fill = Counts), color = "gray80") +
        geom_text(aes(label = Counts), size = 3.4) + 
    #scale_fill_viridis(option = "plasma")
    scale_fill_gradient(low = "aliceblue", high = "orange") + 
    scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
    theme_minimal(base_size = 14) + 
    xlab("") + ylab("") + 
    ggtitle("Immune classes across cancer types",) +
    theme(panel.grid = element_blank(),
          axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          legend.position = "none",
          plot.title = element_text(size = 12),
          plot.margin = margin(t = 0,  # Top margin
                             r = 0,  # Right margin
                             b = 0,  # Bottom margin
                             l = 0)) # Left margin)

ggsave(plot = tcga.immune.states.plot, 
     file = file.path(fig.dir, "tcga.immune.states.heatmap.png"),
                      width = 5, height = 5, bg = "white")

cairo_pdf(filename = file.path(fig.dir, "tcga.immune.states.heatmap.pdf"),
        width = 4.5, height = 4.5)
print(tcga.immune.states.plot)
dev.off()

# ggsave(plot = tcga.immune.states.plot, 
#      file = file.path(fig.dir, "tcga.immune.states.heatmap.pdf"),
#                       width = 5, height = 5)
```
```{r}
tcga.immune.tissues = tcga.immune.states %>% 
    mutate(Immune.Subtype = ifelse(Immune.Subtype == "NA", "CNA", Immune.Subtype)) %>% 
    pivot_wider(id_cols = c(Cancer.Types, Sample.Names, Accuracy),
            names_from = Immune.Subtype, values_from = Immune.Subtype) %>% 
    mutate(across(C1:CNA, ~ifelse(is.na(.x), 0, 1))) %>% 
    rename(donor_id = Sample.Names)

rownames(tcga.immune.tissues) = tcga.immune.tissues$donor_id

tcga.immune.sigs = tcga.immune.states %>% select(-Immune.Subtype)
```

```{r path-sig-prep}
PATH_MIN_TISSUES = 30

abundant.tissues = which(tcga.immune.sigs$Cancer.Types %>% 
                             table() > PATH_MIN_TISSUES) %>% names()

cat(abundant.tissues, sep = "\n")
# number of total samples
tcga.immune.sigs$Cancer.Types %in% abundant.tissues %>% sum()

```

### Interactions between TCGA signatures and immune states

```{r}
immune.tissue.odds.ratio = pcawg_sig_pathway_int(sigs.input = tcga.immune.sigs,
                                 pathways.input = tcga.immune.tissues,
                                 interaction_function = get_sig_path_assocs, 
                                 path.min.tissues = 30,
                                 p.val.threshold = 0.05,
                                 p.adjust = FALSE,
                                 method = "BH")


for (tissue in names(immune.tissue.odds.ratio)) {
   
    if (any(abs(immune.tissue.odds.ratio[[tissue]]) > 0) ) {
        cat(tissue, "\n")
        int.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio[[tissue]], 
                                        title = tissue)
        
        ggsave(plot = int.heatmap,
               filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                                    paste0("TCGA", tissue, "_sig_pathway.dotplot.tcga.pdf")),
               height = 5, width = 5, bg = "white", device = cairo_pdf)
    }
}
tissue = "Cervix_CA"
int.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio[[tissue]][1, 1, drop = FALSE], 
                                        title = tissue, limits = c(-3, 3))

ggsave(plot = int.heatmap,
               filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                                    paste0("TCGA", tissue, "_sig_pathway.dotplot.tcga.pdf")),
               height = 3, width = 3.5, bg = "white", device = cairo_pdf)


tissue = "Head_SCC"
int.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio[[tissue]][c(1,3), , drop = FALSE], 
                                        title = tissue, limits = c(-3, 3))

ggsave(plot = int.heatmap,
               filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                                    paste0("TCGA", tissue, "_sig_pathway.dotplot.tcga.pdf")),
               height = 3.5, width = 3.5, bg = "white", device = cairo_pdf)


tissue = "Uterus_AdenoCa"
int.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio[[tissue]], 
                                        title = tissue, limits = c(-3, 3))

ggsave(plot = int.heatmap,
               filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                                    paste0("TCGA", tissue, "_sig_pathway.dotplot.tcga.pdf")),
               height = 3.5, width = 3.5, bg = "white", device = cairo_pdf)
```

```{r}

immune.tissue.odds.ratio.unadjusted = pcawg_sig_pathway_int(sigs.input = tcga.immune.sigs,
                                 pathways.input = tcga.immune.tissues,
                                 interaction_function = get_sig_path_assocs, 
                                 path.min.tissues = 30,
                                 p.val.threshold = 0.05,
                                 p.adjust = FALSE,
                                 method = "BH")


for (tissue in names(immune.tissue.odds.ratio.unadjusted)) {
   
    if (any(abs(immune.tissue.odds.ratio.unadjusted[[tissue]]) > 0) ) {
        cat(tissue, "\n")
        int.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio.unadjusted[[tissue]], 
                                        title = tissue)
        
        ggsave(plot = int.heatmap,
               filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                                    paste0("TCGA", tissue, "_sig_pathway_unadjusted.dotplot.png")),
               height = 5, width = 6, bg = "white")
    }
}

```
```{r}

immune.OR.plot.input = immune.tissue.odds.ratio.unadjusted

for (tissue in names(immune.OR.plot.input) ) {
    if (length(immune.OR.plot.input[[tissue]]) == 0) {
        next
    }
    colnames(immune.OR.plot.input[[tissue]]) = immune.class.mapping[ colnames(immune.OR.plot.input[[tissue]]) ]
}
 
pp.immune.odds.ratio.unadjusted = plot_all_counts(immune.OR.plot.input, 
                                                  threshold = 0.2, psize = 5,
                                                    expand.mult = c(0.03, 0.08)) 

ggsave(plot = pp.immune.odds.ratio.unadjusted,
               filename = file.path(fig.dir,
                                    "TCGA_summarized_immune_sig_unadjusted.dotplot.pdf"),
               height = 1.6, width = 3.7, bg = "white", device = cairo_pdf)
```


```{r}
immune.tissues.odds.ratio.lists = get_interaction_tissues(immune.tissue.odds.ratio.unadjusted)

write.table(as.data.frame(immune.tissues.odds.ratio.lists$pos.tissues), 
          file = here("supp_data", "TCGA_sig_immune_positive_interaction_tissue_summaries.tsv"),
          row.names = TRUE, col.names = NA, sep = "\t", quote = FALSE)
write.table(as.data.frame(immune.tissues.odds.ratio.lists$neg.tissues), 
          file = here("supp_data", "TCGA_sig_immune_negative_interaction_tissue_summaries.tsv"),
          row.names = TRUE, col.names = NA, sep = "\t", quote = FALSE)

```


```{r}
tcga.immune.state.summary = tcga.immune.states %>% 
    ggplot(aes(x = Immune.Subtype, y = after_stat(count))) + 
    geom_bar(fill = "dodgerblue4") + 
    theme_classic() + 
    scale_x_discrete(labels = c("C1" = "Wound healing",
                         "C2" = "INF-\u03B3\ndominant",
                         "C3" = "Inflammatory",
                         "C4" = "Lymphocyte\ndepleted",
                         "C5" = "Immunologically\nquiet",
                         "C6" = "TGF-\u03B2 dominant",
                         "CNA" = "CNA")) + 
    theme(axis.text.x = element_text(angle = 90, v = 0.5, h = 1, size = 13),
          axis.title.x = element_blank(),
          plot.margin = margin(1, 0,0,0, "cm") ) + 
    geom_text(stat='count', aes(label=..count..), vjust=-1) + 
    ylim(0,1500)

ggsave(plot = tcga.immune.state.summary, 
       filename = file.path(fig.dir,"tcga.immune.state.summaries.pdf"),
       width = 4, height = 4, device = cairo_pdf)
```
 
### Interaction signatures in individual tissues
 
```{r}
tcga.immune.tissues = as.data.frame(tcga.immune.tissues)
rownames(tcga.immune.tissues) = tcga.immune.tissues$donor_id
rownames(tcga.immune.sigs) = tcga.immune.sigs$Sample.Names

colnames(tcga.immune.tissues) = sapply( colnames(tcga.immune.tissues), 
                                          function(x) 
                                              {
                                              if (x %in% names(immune.class.mapping )) 
                                                  {
                                                  return(immune.class.mapping[x])
                                                  } else {
                                                      return(x)}
                                              }
                                          )
```
 

```{r}
tcga.colon.immune.states = pathways_signatures_heatmap(
    tissue = "ColoRect_AdenoCa",
    signatures = tcga.immune.sigs, 
    pathways = tcga.immune.tissues, 
    border_color = NA,
     angle_col = 90)

ggsave(plot = tcga.colon.immune.states, 
       filename = file.path(fig.dir, "tcga.colon.immune.states.heatmap.pdf"),
       width = 4, height = 4, device = cairo_pdf)

```

```{r}
tcga.uterine.immune.states = pathways_signatures_heatmap(
    tissue = "Uterus_AdenoCa", 
    signatures = tcga.immune.sigs, 
    pathways = tcga.immune.tissues, 
    border_color = NA, angle_col = 90)

ggsave(plot = tcga.uterine.immune.states, 
       filename = file.path(fig.dir, "tcga.uterus.immune.states.heatmap.pdf"),
       width = 4, height = 4, device = cairo_pdf)
```


```{r}
tissue = "ColoRect_AdenoCa" 

colnames(immune.tissue.odds.ratio[[tissue]]) = c("Wound\nhealing", "INF-\u03B3\ndominant")

colorectal.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio[[tissue]], 
                                        title = tissue)

ggsave(plot = colorectal.heatmap,
       filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                            paste0(tissue, "_sig_pathway.dotplot.TCGA.pdf")),
       height = 4, width = 4, bg = "white", device = cairo_pdf)

```


```{r}
tissue = "Uterus_AdenoCa" 

colnames(immune.tissue.odds.ratio[[tissue]]) = c("Wound\nhealing", "INF-\u03B3\ndominant")

uterine.heatmap = ggheatmap_wrapper(immune.tissue.odds.ratio[[tissue]], 
                                        title = tissue)

ggsave(plot = colorectal.heatmap,
       filename = file.path(fig.dir, "immune_to_signature", "by_tissues", "oddsratio",  
                            paste0(tissue, "_sig_pathway.dotplot.TCGA.pdf")),
       height = 3.5, width = 4, bg = "white", device = cairo_pdf)
```

 