---
title: "Survival analysis of signature-signature interactions in TCGA"
output: 
  html_document:
    df_print: paged
---

```{r}
# .rs.restartR()
rm(list = ls())
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```

```{r load-packages}
library(here)
library(survival)
library(survminer)

source(here("R/load_packages.R"))
library(gridExtra)

input.dir = here("data/RDS/TCGA/metadata")

out.dir = here("data/RDS/TCGA/sig_sig_survivals")
fig.dir = here("figures/sig_sig_survivals")

for (dir.name in c(fig.dir, out.dir)) {
    if (! file.exists(dir.name) ) {
        dir.create(dir.name, recursive = TRUE)
    }
}
```

### Reading in clinical and signature data

```{r}
TCGA.full.subset.ann = readRDS(file = here("data/RDS",
                                           "TCGA/signatures/TCGA.full.subset.ann.RDS"))   
TCGA.clin.df = readRDS(file = file.path(input.dir, "TCGA.clin.df.RDS") )

positive.sig.sig = read.delim(file = here("supp_data", 
                                        "TCGA_positive_interaction_tissue_summaries.tsv"),
                              row.names = 1)

negative.sig.sig = read.delim(file = here("supp_data", 
                                        "TCGA_negative_interaction_tissue_summaries.tsv"),
                            row.names = 1)
```


### Survival models for positive interactions

```{r}
pos.plotlist = get_surv_plotlist(positive.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "TCGA_positive_interactions_survivals_totmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()


pos.plotlist = get_surv_plotlist(positive.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = FALSE, 
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "TCGA_positive_interactions_survivals_nontotmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()


pos.plotlist = get_surv_plotlist(positive.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = TRUE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "TCGA_positive_interactions_survivals_totmut_binary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(pos.plotlist) ) {
    try({print(pos.plotlist[[i]] ) })
}
dev.off()
```


```{r}
pos.coxlist = get_surv_coxlist(positive.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(pos.coxlist, file = file.path(out.dir, "pos.coxlist.totmut.nonbinary.RDS"))



pos.coxlist = get_surv_coxlist(positive.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = FALSE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(pos.coxlist, file = file.path(out.dir, "pos.coxlist.nototmut.nonbinary.RDS"))
```


```{r}
pos.picked.models = get_surv_best_model(positive.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(pos.picked.models, file = file.path(out.dir, "tcga.pos.sig.sig.picked.models.RDS"))
```

### Survival models for negative interactions

```{r}
neg.plotlist = get_surv_plotlist(negative.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = TRUE,
                                 tmb.logged = TRUE,
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "TCGA_negative_interactions_survivals_totmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()


neg.plotlist = get_surv_plotlist(negative.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = FALSE, 
                                 binary.status = FALSE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "TCGA_negative_interactions_survivals_nontotmut_nonbinary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()


neg.plotlist = get_surv_plotlist(negative.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = TRUE,
                                 legend.pos = c(0.8, 0.8))

pdf(file.path(fig.dir, "TCGA_negative_interactions_survivals_totmut_binary.pdf"),
    onefile = TRUE, width = 6, height = 8)

for (i in 1:length(neg.plotlist) ) {
    try({print(neg.plotlist[[i]] ) })
}
dev.off()
```

```{r}
neg.coxlist = get_surv_coxlist(negative.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = TRUE, 
                               tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(neg.coxlist, file = file.path(out.dir, "neg.coxlist.totmut.nonbinary.RDS"))


neg.coxlist = get_surv_coxlist(negative.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = FALSE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(neg.coxlist, file = file.path(out.dir, "neg.coxlist.nototmut.nonbinary.RDS"))
```


```{r}
neg.picked.models = get_surv_best_model(negative.sig.sig, 
                                 dataset = TCGA.full.subset.ann,
                                 clin.df = TCGA.clin.df,
                                 with.total.muts = TRUE, 
                                 tmb.logged = TRUE,
                                 binary.status = FALSE)
saveRDS(neg.picked.models, file = file.path(out.dir, "tcga.neg.sig.sig.picked.models.RDS"))
```


### Specific interactions

```{r}
ColoRect_AdenoCa_MMR_SBS40 = survival_for_interactions(dataset = TCGA.full.subset.ann, 
                                                      signatures = c("MMR", "SBS40"), 
                                                      tissues = "ColoRect_AdenoCa", 
                                                      clin.df = TCGA.clin.df,
                                                      legend_pos = c(0.7, 0.22),
                                                      with.total.muts = TRUE,
                                                      tmb.logged = TRUE,
                                                      binary.status = FALSE,
                                                      conf.int = TRUE)

ggsave(plot = ColoRect_AdenoCa_MMR_SBS40$survP$plot,
       filename = file.path(fig.dir, "TCGA_ColoRect_AdenoCa_MMR_SBS40.survivals.pdf"),
       width = 4, height = 3.5)


ColoRect_AdenoCa_MMR_SBS40_ggforest = ggforest(model = ColoRect_AdenoCa_MMR_SBS40$coxout, data = ColoRect_AdenoCa_MMR_SBS40$survival.df)

ggsave(plot = ColoRect_AdenoCa_MMR_SBS40_ggforest,
       filename = file.path(fig.dir, "TCGA_ColoRect_AdenoCa_MMR_SBS40_ggforest.ggforest.pdf"),
       width = 6, height = 2.3)
```

### Case of Stomach AdenoCa

```{r}
stomach.sigs = TCGA.full.subset.ann %>% filter(Cancer.Types == "Stomach_AdenoCa")
stomach.sigs$TMB = rowSums(stomach.sigs[4:ncol(stomach.sigs)])
rownames(stomach.sigs) = substr(stomach.sigs$Sample.Names, 1, 12)
stomach.clin = TCGA.clin.df %>% filter(bcr_patient_barcode %in% 
                                           rownames(stomach.sigs)) %>% unique()
rownames(stomach.clin) = stomach.clin$bcr_patient_barcode
stomach.clin = stomach.clin[rownames(stomach.sigs),]


stomach.combined = cbind(stomach.sigs, stomach.clin)

stomach.combined = stomach.combined %>% mutate(status = ifelse(
    MMR > 0 & SBS17 > 0, "MMR + SBS17", 
    ifelse (APOBEC > 0 & SBS40 > 0,"APOBEC+SBS40", "Other")) ) %>% 
    rename(survival_time = times, vital_status = patient.vital_status)


stomach.surv = survfit(Surv(survival_time, vital_status) ~ status, data = stomach.combined)


P = ggsurvplot(stomach.surv, data = stomach.combined,
                       font.legend = c(14, "plain", "black"),
                       legend.title = element_blank(),
                       legend.labs = gsub("status=", "", names(stomach.surv$strata)),
                       # palette = "jco",
                       xlab = "Days",
                       conf.int = TRUE) + 
            guides(colour = guide_legend(nrow = length(stomach.surv$strata)))
        
P$plot = P$plot + theme(legend.background = element_rect(fill='transparent'),
                        legend.box.background = element_rect(fill='transparent', size = 0))

ggsave(filename = file.path(fig.dir, "tcga.stomach.MMR_SBS17.APOBEC_SBS40.Others.survival.pdf"),
                            width = 4, height = 3)
```

