---
title: "The notebook explores mutation types of TP53 pathway genes in PAAD, PRAD, CLL"
output: html_notebook
---


```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```


```{r load-packages, message=FALSE}
library(here)
fig.dir = here("figures/TP53_path_muts")

if(! file.exists(fig.dir)){
    dir.create(fig.dir, recursive = TRUE)
}

source(here("R/load_packages.R"))


ref_genome <- "BSgenome.Hsapiens.UCSC.hg38"
library(ref_genome, character.only = TRUE)

library(MutationalPatterns)
```

```{r}
input.dir = here("data/TP53_mutations")

tissues = list.dirs(input.dir, recursive = FALSE, full.names = FALSE)
```

```{r}
get_tissue_mut_dist = function(tissue) {
    gd.files = list.files(path = file.path(input.dir, tissue), 
                          pattern = "Distribution-[A-Z0-9]+-[A-Z]+.tsv", full.names = TRUE)
    
    mut.types = list()
    
    for (f in gd.files) {
        
        gene.name = gsub(".*Distribution-([A-Z0-9]+)-[A-Z]+.tsv", "\\1", f)
        
        f.muts = read.delim(f)
        
        f.muts = f.muts %>% 
            mutate(chr = paste0("chr", stringr::str_split(Mutation..GRCh38., ":") %>% 
                       map_chr(., 1)),
                   position = as.numeric(stringr::str_split(Mutation..GRCh38., ":") %>% 
                       map_chr(., 2)),
                   mutation = stringr::str_split(Mutation..GRCh38., ":") %>% 
                       map_chr(., 3)) %>% 
            filter(grepl("[ACTG]>[ACTG]", mutation)) %>% 
            mutate(REF = stringr::str_split(mutation, ">") %>% 
                       map_chr(., 1),
                   ALT = stringr::str_split(mutation, ">") %>% 
                       map_chr(., 2))
        
        f.granges = GRanges(seqnames = f.muts$chr, 
                           ranges = IRanges(start = f.muts$position, 
                                            end = f.muts$position + 1), 
                           seqinfo = seqinfo(BSgenome::getBSgenome(ref_genome)), 
                           REF = f.muts$REF, ALT = f.muts$ALT)
        
        f.mut.type = mut_type_occurrences(f.granges, ref_genome)
        
        mut.types[[gene.name]] = f.mut.type
    }
    
    return(mut.types)
}

```

```{r}
paad.types = get_tissue_mut_dist("PAAD")
```

