#' For signature interactions calculated for two datasets and all the tissues
#' makes a split-cell "heatmap" with numbers in either sides of the heatmap-cell
#' the number of positive/negative interactions across tissues
#' 
#' @param summary.matrix The output generated by summarize_SP_SA_by_tissues function
#' 
#' @return ggplot object

plot_all_counts = function(list.of.sig.elems, dataset_top = "SigProfiler", ggstar = TRUE) {
    
    gg.final.dt = c()
    
    # all.sigs = do.call(c, lapply(summary.matrix, function(x) colnames(x)) ) %>%
    #     unique()
    
    all.rows = do.call(c, lapply(list.of.sig.elems, function(x) rownames(x))) %>% 
        unique()
    
    all.cols = do.call(c, lapply(list.of.sig.elems, function(x) colnames(x))) %>% 
        unique()
    
    for (rowelem in all.rows) {
        for (colelem in all.cols) {
            unlist(sapply(list.of.sig.elems, 
                          function(x) as.data.frame(x)[rowelem, colelem]))
        }
    }
    
    
    
    
    for (dataset in names(summary.matrix)) {
        
        matoi = summary.matrix[[dataset]]
        
        pairwise.indeces = combn(all.sigs, 2) %>% t()
        
        if (! dataset == dataset_top) {
            pairwise.indeces = pairwise.indeces[, c(2,1)]
        }
        
        ggdat = pairwise.indeces %>% as.data.frame() %>%
            as_tibble() %>% rename(sig1 = V1, sig2 = V2) 
        
        poss = sapply(matoi[ pairwise.indeces] , function(x) x$pos)
        ggdat$pos = lapply(poss, function(x) if (is.null(x)) 0 else x) %>% unlist()
        
        negs = sapply(matoi[ pairwise.indeces] , function(x) x$neg)
        ggdat$neg = lapply(negs, function(x) if (is.null(x)) 0 else x) %>% unlist()
        
        ggdat = ggdat %>% 
            pivot_longer(cols = c(pos, neg), 
                         names_to = "int.type", values_to = "count") %>% 
            mutate(dataset = dataset)
        gg.final.dt = rbind(gg.final.dt, ggdat)
    }
    
    sig1sum = gg.final.dt %>% group_by(sig1) %>% rename(sig = sig1) %>%
        dplyr::summarize(tot_count = sum(abs(count) ) ) %>% rename(sig1c = tot_count)
    
    sig2sum = gg.final.dt %>% group_by(sig2) %>% rename(sig = sig2) %>%
        dplyr::summarize(tot_count = sum(abs(count) ) ) %>% rename(sig2c = tot_count)
    
    rm.sigs = full_join(sig1sum, sig2sum, by = "sig") %>% replace(is.na(.), 0) %>%
        mutate(sum_counts = sig1c + sig2c) %>% 
        filter(sum_counts < 5) %>% pull(sig)
    
    cat(rm.sigs, sep = "\t")
    gg.final.dt = gg.final.dt %>% filter(!sig1 %in% rm.sigs, !sig2 %in%  rm.sigs)
    
    active.sigs = gg.final.dt$sig1 %>% unique()
    active.sigs = setNames(1:length(active.sigs), active.sigs )
    
    
    gg.final.dt = gg.final.dt %>% mutate(
        x = active.sigs[sig1],
        y = active.sigs[sig2]
    )
    
    if (ggstar) {
        
        gg.final.dt = gg.final.dt %>% 
            mutate(xlab = ifelse(int.type == "pos", x - 0.2, x + 0.2), 
                   ylab = ifelse(int.type == "pos", y - 0.15, y + 0.15))
        
        gg.final.dt = gg.final.dt %>% 
            mutate(ggstar.t = ifelse(int.type == "neg", 19, 20) )
        
        gg.final.dt = as.data.frame(gg.final.dt)
        
        d =  ggplot(gg.final.dt, aes(x = x, y = y, # color = int.type,
                                     shape = int.type, label = count)) + 
            geom_text(aes(x = xlab, y = ylab, colour = count), 
                      size = 4) + 
            scale_color_gradient2(low = scales::muted("blue"),
                                  mid = "gray90",
                                  high = scales::muted("red")) +
            #  scale_shape_manual(values=c("\u25E9","\u25EA")) +
            geom_star(data = gg.final.dt, 
                      aes_(x=~x, y=~y,  starshape=~ggstar.t), 
                      size = 2.5,
                      show.legend=FALSE, color = "gray40") +
            scale_starshape_identity() 
    } else {
        
        gg.final.dt = gg.final.dt %>% 
            mutate(xlab = ifelse(int.type == "pos", x - 0.2, x + 0.2), 
                   ylab = ifelse(int.type == "pos", y + 0.15, y - 0.15))
        
        gg.final.dt = as.data.frame(gg.final.dt)
        
        d <- ggplot(gg.final.dt, aes(x = x, y = y, color = int.type,
                                     shape = int.type, label = count)) +
            geom_point(size = 4.5) +
            geom_text(aes(x = xlab, y = ylab), size = 2, color = "white", fontface = "bold") +
            scale_shape_manual(values=c("\u25E4","\u25E2")) +
            scale_color_brewer(palette = "Set1") 
    }
    
    d = d +
        theme_minimal() +
        theme( panel.border = element_blank(),
               panel.grid = element_blank(),
               panel.grid.major = element_blank(),
               panel.grid.minor = element_blank(),
               # axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
               axis.text.x = element_text(angle = 45, margin = margin(r = 0, t = 0, b = 0, l = 0),
                                          hjust = 0),
               axis.text.y = element_text(margin = margin(r = 0)),
               axis.title = element_blank(),
               legend.position = "none"
        ) +
        scale_x_continuous(# expand = expansion(mult = c(0.01, 0.01)),
            breaks = active.sigs,
            labels = names(active.sigs),
            position = "top") +
        scale_y_continuous(# expand = expansion(mult = c(0.01, 0.01)),
            breaks = active.sigs,
            labels = names(active.sigs))
    
    return(d)
}
